### ISSUE TITLE
Height and Weight Prediction

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#10]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Height and Weight Prediction
:red_circle: **Aim** : Build a predictive model for determining height or weight of a person. Implement a linear regression model that will be used for predicting height or weight.
:red_circle: **Dataset** : http://wiki.stat.ucla.edu/socr/index.php/SOCR_Data_Dinov_020108_HeightsWeights
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/abhisheks008/ML-Crate/tree/main/Project-Demo-Folder

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- Are you a participant of SWOC 2.0?
    - [ ] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by shivangisehgal** [comment]
Full name : Shivangi Sehgal
GitHub Profile Link : https://github.com/shivangisehgal
Participant ID : 909
Approach for this Project : Perform EDA, try different regression models to predict Weight based on Height (or vice versa) and find best fitted model by evaluating their errors.
Are you a participant of SWOC 2.0?
 YES

**Comment by abhisheks008** [comment]
Issue assigned to you @shivangisehgal
