### ISSUE TITLE
World Mortality Rate Analysis and Prediction

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#110]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : World Mortality Rate Analysis and Prediction
:red_circle: **Aim** : This project will help us in analyzing and predicting the mortality rate using the provided dataset.
:red_circle: **Dataset** : https://www.kaggle.com/navinmundhra/world-mortality
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- What is your participant role?
    - [ ] SWOC 2.0 Participant.
    - [ ] JWOC 2022 Participant.
    - [ ] Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by nishtha2405** [comment]
I want to work on this issue under JWOC

**Comment by abhisheks008** [comment]
Follow the guidelines and comment out with proper details mentioned in the issue @nishtha2405

**Comment by PiyushBL45t** [comment]
@abhisheks008 I would like to work on this issue.
Name: Piyush Bhujbal
GitHub profile link: https://www.github.com/PiyushBL45t

Approach for this project: 
1. Filter the dataset.
2. Analyze the columns.
3. Take out useful columns.
4. Dropping out useless columns.
5. Making visualizations.
6. Implementing ML algorithms if necessary.
7. Derive useful results from the visuals.

Participant Role: HSOC participant

**Comment by abhisheks008** [comment]
You need to create a prediction model, and before that a good EDA is required.

Issue assigned to you @PiyushBL45t

**Comment by PiyushBL45t** [comment]
Thanks @abhisheks008/ML-Crate
***@***.***>

**Comment by PiyushBL45t** [comment]
I will do it
