### ISSUE TITLE
Top Cryptocurrency Analysis and Prediction

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#118]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Top Cryptocurrency Analysis and Prediction
:red_circle: **Aim** : This project will analyze the data and identify the top crypto of 2022.
:red_circle: **Dataset** : https://www.kaggle.com/majyhain/top-100-cryptocurrency-2022
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- What is your participant role?
    - [ ] SWOC 2.0 Participant.
    - [ ] JWOC 2022 Participant.
    - [ ] Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aryashahi** [comment]
Name: Arya Shahi
GitHub ID: aryashahi
Approach: perform EDA on the dataset and train it on different algorithms
What's your participant role:  ☑ JWOC 2022 Participant.

**Comment by abhisheks008** [comment]
Issue assigned to you @aryashahi

**Comment by abhisheks008** [comment]
What's the update here @aryashahi

**Comment by aryashahi** [comment]
@abhisheks008 datacleaning on the given data is a bit complicated for me. I'm working on it. will let you know after figuring it out.

**Comment by Avik-creator** [comment]
@abhisheks008 do we need to make ML models in this?

**Comment by abhisheks008** [comment]
Yes you need! @Avik-creator

**Comment by Avik-creator** [comment]
@abhisheks008  thanks for clearing the doubt

**Comment by Avik-creator** [comment]
Please assign me this @abhisheks008

**Comment by abhisheks008** [comment]
This project has two sections, first part is all about analysis (what you have done in your last analysis projects), need to conclude some conclusions. After that, you need to apply the models to predict the prices of the top crypto according to your analysis. Then you need to find the best possible model that is going to be fitted here.

@Avik-creator

**Comment by Avik-creator** [comment]
@abhisheks008 like linear regression, Random forest, decision tree classifiers right?

**Comment by Avik-creator** [comment]
Ok I see
