### ISSUE TITLE
Real / Fake Job Posting Prediction

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#126]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Real / Fake Job Posting Prediction
:red_circle: **Aim** : This project is to identify the Real/Fake job postings.
:red_circle: **Dataset** : https://www.kaggle.com/shivamb/real-or-fake-fake-jobposting-prediction
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- What is your participant role?
    - [ ] SWOC 2.0 Participant.
    - [ ] JWOC 2022 Participant.
    - [ ] Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by snega16** [comment]
SNEGA S
https://github.com/snega16
Approach - Creating ML models after data analysis and EDA.
What is your participant role?
- [x] JWOC 2022 Participant.

**Comment by abhisheks008** [comment]
One issue at a time @snega16

**Comment by srini047** [comment]
- **Full Name:** Sriniketh J
- **GitHub Profile Link:** [srini047](https://github.com/srini047/)
- **Approach for this Project:** Building 2 to 3 Models like Decision Tree, SVC after Data Preprocessing and Visualisation
- **Participant Role:** **JWOC**

**Comment by abhisheks008** [comment]
Fix the little problem in your last PR and you are good to go with this issue @srini047

**Comment by abhisheks008** [comment]
What's the update here @srini047

**Comment by srini047** [comment]
> What's the update here @srini047

I have made 2 models and doing the third one. And just need to do the README file alone at the end. Need more 2-3 hours. Before which I will make a PR.

**Comment by abhisheks008** [comment]
Good job, go ahead with your work. Thanks for the update @srini047
