### ISSUE TITLE
Narendra Modi - Text Speeches Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#127]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Narendra Modi - Text Speeches Analysis
:red_circle: **Aim** : This project is to analyze the speeches of Narendra Modi.
:red_circle: **Dataset** : https://www.kaggle.com/adiamaan/modi-speeches
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- What is your participant role?
    - [ ] SWOC 2.0 Participant.
    - [ ] JWOC 2022 Participant.
    - [ ] Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Adi9235** [comment]
I want to work on this issue under JWOC

**Comment by abhisheks008** [comment]
Follow the issue guidelines and mention all the required details properly before taking the issue @Adi9235

**Comment by Adi9235** [comment]
* Full name : Aditya Tomar
* Github Profile Link : https://github.com/Adi9235
* Approach for this Project : To create ML models after data analysis and proper visualization
* What is your participant role?
    - [x]  JWOC 2022 Participant

**Comment by abhisheks008** [comment]
Issue assigned to you @Adi9235

**Comment by abhisheks008** [comment]
What's the update here @Adi9235

**Comment by Adi9235** [comment]
I am working on it @abhisheks008 it is the first time so it is taking me time to complete.

**Comment by abhisheks008** [comment]
Yeah it's ok. Thank you for responding and the update. @Adi9235

**Comment by abhisheks008** [comment]
What's the update here @Adi9235

**Comment by Adi9235** [comment]
I m working on it

**Comment by divyansh-2707** [comment]
Name-Divyansh Singh
Git Hub-https://github.com/divyansh-2707
Approach for this Project - To create ML models after data analysis and proper visualization
Participant Role-SSOC'24

**Comment by HarshRaj29004** [comment]
Name : Harsh Raj

GitHub Profile : https://github.com/HarshRaj29004

Approach for this Project :
1) I will do data cleaning removing or merging columns to apply EDA on it.
2) Then will perform EDA on dataset, like analyzing the most frequently used words and phrases in the speeches,  determine the overall sentiment of each speech, etc.
3) This all will be visually represented.

What is your participant role? SSOC'24 participant

**Comment by abhisheks008** [comment]
Use different plots and analysis methods for analysing the dataset.

Assigned @HarshRaj29004
