### ISSUE TITLE
Toxic Comment Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#129]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Toxic Comment Analysis
:red_circle: **Aim** : This project will analyze the toxic comments.
:red_circle: **Dataset** : https://www.kaggle.com/devkhant24/toxic-comment
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- What is your participant role?
    - [ ] SWOC 2.0 Participant.
    - [ ] JWOC 2022 Participant.
    - [ ] Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by nishtha2405** [comment]
I want to work on this issue under JWOC

**Comment by abhisheks008** [comment]
Follow the issue guidelines and mention all the required details properly before taking the issue @nishtha2405

**Comment by nishtha2405** [comment]
Nishtha Pandey
 https://github.com/nishtha2405
Few of the approaches for the project  are implemented using simple lists, Logistic Regression, Naive bayes and CNN. 
JWOC 2022 Participant

**Comment by abhisheks008** [comment]
Issue assigned to you @nishtha2405

**Comment by abhisheks008** [comment]
What's the update here @nishtha2405

**Comment by nishtha2405** [comment]
working on it

**Comment by nishtha2405** [comment]
I am unable to solve this issue, please assign it to someone else and I would like to work on other issues

**Comment by abhisheks008** [comment]
Okay! @nishtha2405

**Comment by KhanSumaiyaS** [comment]
Hello I would like to work on this project. Please assign it to me
Full name : Khan Sumaiya SaifulAli
GitHub Profile Link : https://github.com/KhanSumaiyaS
Participant ID (If not, then put NA) : NA
Approach for this Project : I would first perform Hyperparameters and Helper Functions in order to achieve the best result. The next step would be cleaning the data and preprocessing of data. Then the modelling and training of data by define LSTM network that has feedback connections that can find relationship of samples in the sequential input and then model predicts whether test dataset is toxic or not.
What is your participant role? - Contributor

**Comment by abhisheks008** [comment]
Issue assigned to you @KhanSumaiyaS

**Comment by abhisheks008** [comment]
Issue has been un-assigned from you due to inactivity.
@KhanSumaiyaS

**Comment by Aryanmartinian** [comment]
Hi, I would like to contribute to this under KWOC ' 23
Full Name - Aryan Mishra
Github Profile Link - https://github.com/Aryanmartinian
Participant Role - Contributor (KWOC '23)
Participant ID - NA
Approach - First I will apply EDA on the dataset then using text classification i will make a machine learning model to predict the toxicity in the above given dataset.

**Comment by abhisheks008** [comment]
Issue assigned to you @Aryanmartinian

**Comment by CoderOMaster** [comment]
Please assign me

**Comment by abhisheks008** [comment]
@CoderOMaster can you please share your approach?

**Comment by CoderOMaster** [comment]
@abhisheks008 I will implement Roberta,bert,gru,lstm

**Comment by abhisheks008** [comment]
@CoderOMaster please mention the details as per the given template. It will be better for me to assign issues, otherwise I need to ask you each and every time about the open source event. As this project repo is part of two different open source events, it will be better to use the template and put your comment.

**Comment by CoderOMaster** [comment]
Hello I would like to work on this project. Please assign it to me
Full name : Keshav Arora 
GitHub Profile Link : https://github.com/CoderOMaster 
Participant ID (If not, then put NA) : NA
Approach for this Project : I would first perform Eda,cleaning the database, implement Roberta,bert,Ann(embedding),Lstm
What is your participant role? - Jwoc Mentee

**Comment by abhisheks008** [comment]
Assigned under JWOC @CoderOMaster
