### ISSUE TITLE
Uber Pickup Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#13]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Uber Pickup Analysis
:red_circle: **Aim** : To analyze the data of the customer rides and visualize the data to find insights that can help improve business. Data analysis and visualization is an important part of data science. They are used to gather insights from the data and with visualization you can get quick information from the data.
:red_circle: **Dataset** : https://www.kaggle.com/fivethirtyeight/uber-pickups-in-new-york-city
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/abhisheks008/ML-Crate/tree/main/Project-Demo-Folder

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- Are you a participant of SWOC 2.0?
    - [ ] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by deepthi1107** [comment]
Full name : Deepthi M
GitHub Profile Link : https://github.com/deepthi1107
Participant ID : 294
Approach for this Project: EDA, SVM, random forest, decision tree
Are you a participant of SWOC 2.0?
 YES

**Comment by abhisheks008** [comment]
Issue assigned to you @deepthi1107

**Comment by Cody-coder017** [comment]
Full name : Venkatakrishnan R
GitHub Profile Link :https://github.com/Cody-coder017
Participant ID : 1104
Approach for this Project : Using time series models to predict the pickups
I would like to work on this issue

**Comment by abhisheks008** [comment]
@Cody-coder017 first complete the issue of Jeopardy bot then only you'll be assigned to any new issues.

**Comment by abhisheks008** [comment]
Issue assigned to you @Cody-coder017

**Comment by abhisheks008** [comment]
Hello @Cody-coder017 , what's the update here?

**Comment by Cody-coder017** [comment]
At a good stage proceeding, encountered some issues with my desktop ,so just holding up the works,trying to do asap

**Comment by krishna-NIT** [comment]
Sure, I want to be in the waiting list, if suppose in case, due some issue, if assigned one is not able to complete
Then I'll  take it from here

Full name: Shrikrushna Bhagwat
GitHub Profile Link: https://github.com/krishna-NIT
Participant ID: 930
Approach for this Project: EDA, SVM, random forest, decision tree, time series module for predictions
Are you a participant of SWOC 2.0?
YES

**Comment by Cody-coder017** [comment]
@abhisheks008  there is a steady progress EDA is done working on time series and readme file 
since my end semester is on i could not work at expected but im trying my best

**Comment by krishna-NIT** [comment]
@Cody-coder017 Don't worry, the delay is accepted, We will be waiting bro, take your time, let me know in case if you need any help, I'll be happy to learn from you too!

**Comment by Cody-coder017** [comment]
@krishna-NIT  sure

**Comment by abhisheks008** [comment]
@Cody-coder017 what's the update here?

**Comment by Cody-coder017** [comment]
need 2 more days , i will complete it

**Comment by abhisheks008** [comment]
Okay. @Cody-coder017
