### ISSUE TITLE
WebMD Drug Reviews

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#131]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : WebMD Drug Reviews
:red_circle: **Aim** : This project will identify the drug reviews and classify them.
:red_circle: **Dataset** : https://www.kaggle.com/rohanharode07/webmd-drug-reviews-dataset
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- What is your participant role?
    - [ ] SWOC 2.0 Participant.
    - [ ] JWOC 2022 Participant.
    - [ ] Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Raghavvvvv** [comment]
Hello Sir,
Full name : Raghav Jha
GitHub Profile Link : https://github.com/Raghavvvvv
Participant ID : NA
Approach for this Project : I would Like to contribute for this project, I will try to use atleast 3-4  Algorithms  to Analyze the Results.

And I will Also Try to solve following questions:

I. Identifying the condition of the patient based on drug reviews?
II. How to predict drug rating based on patient’s reviews?
III. How to visualize drug rating, kind of drugs, types of conditions a patient can have, sentiments based on reviews.

Thank you

**Comment by abhisheks008** [comment]
Nice approach! Issue assigned to you @Raghavvvvv

**Comment by abhisheks008** [comment]
Issue has been un-assigned from you due to inactivity.
@Raghavvvvv

**Comment by pawaspy** [comment]
Full name : Pawas Pandey
GitHub Profile Link :github.com/pawaspy
Participant ID : NA
Approach for this Project : I will use data cleaning and preprocessing and then use different model to train and test the dataset
What is your participant role? IWoC 2.0

**Comment by abhisheks008** [comment]
Assigned @pawaspy
