### ISSUE TITLE
Stanford Car Image Classification

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#151]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Stanford Cars Analysis
:red_circle: **Aim** : Analyze the data of the Stanford Cars.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/jutrera/stanford-car-dataset-by-classes-folder
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- What is your participant role?
    - [ ] SWOC 2.0 Participant.
    - [ ] JWOC 2022 Participant.
    - [ ] Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Nupur2471** [comment]
Full name : Nupur Kelkar 
GitHub Profile Link: https://github.com/Nupur2471
Approach for this Project: Creating a CNN Model for Classification.  Using XGboost and InceptionResNetV2 Model to figure out which has better accuracy.

**Comment by abhisheks008** [comment]
Nice approach. Go ahead, issue assigned to you @Nupur2471

**Comment by abhisheks008** [comment]
Issue has been un-assigned from you due to inactivity.
@Nupur2471

**Comment by rising-star2712** [comment]
Full name : Prince Thakkar
GitHub Profile Link : https://github.com/rising-star2712
Participant ID : NA
Approach for this Project : CNN , XG Boost , with Open CV , this is my first time trying open CV , requesting you to assign this issue to me , would love to work on it 
What is your participant role?

**Comment by rising-star2712** [comment]
waiting for the issue to be assigned and will start the work as soon as possible

**Comment by abhisheks008** [comment]
Issue assigned to you @rising-star2712

**Comment by abhisheks008** [comment]
Unassigned. **ML-Crate** is going to be part of DWOC from Jan, 15, all the unfinished issues will be taken by the contributors of DWOC.

**Comment by Soumya-Kushwaha** [comment]
Hey, @abhisheks008 
I'd like to work on this.

Full name : Soumya Kushwaha
GitHub Profile Link : https://github.com/Soumya-Kushwaha
Participant ID : NA
Approach for this Project : Use YOLO along with Inception

**Comment by abhisheks008** [comment]
Sure why not.
Assigned to you @Soumya-Kushwaha

**Comment by Anwar11234** [comment]
Full name : Ahmed Mohammed  Anwar
GitHub Profile Link : https://github.com/Anwar11234
Participant ID : NA
Approach for this Project : building a computer vision model to detect plate number of a car
What is your participant role? KWOC 2023 Participant.

**Comment by abhisheks008** [comment]
Hey @Anwar11234 sorry for the delay, I was in vacation with my family. Issue assigned to you @Anwar11234
