### ISSUE TITLE
Lottery Prediction

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#165]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Lottery Prediction
:red_circle: **Aim** : Create a prediction model, which will predict the lottery using ML.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/muhammadzain010/lottery-ticket-prediction-based-on-history
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- What is your participant role?
    - [ ] SWOC 2.0 Participant.
    - [ ] JWOC 2022 Participant.
    - [ ] Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Nirvik07** [comment]
@abhisheks008  Dataset link is not working.

**Comment by abhisheks008** [comment]
@Nirvik07 Dataset updated!

**Comment by chandinic10** [comment]
Full name : Chandini Chentamara
GitHub Profile Link : [https://github.com/chandinic10](url)
Participant ID : 
Approach for this Project : Firstly preprocess the data and then perform Exploratory data analysis to perform initial investigation on the provided dataset. The next step would be training the model based on the given dataset, where the model training would be done on the basis of the winning lottery numbers and thus the next lottery winner will be predicted.
What is your participant role?
Contributor

**Comment by Saurabhbangar0** [comment]
Full name : Saurabh Bangar
GitHub Profile Link :https://github.com/Saurabhbangar0
Participant ID :
Approach for this Project : Firstly preprocess the data and then perform Exploratory data analysis to perform initial investigation on the provided dataset. The next step would be training the model based on the given dataset, where the model training would be done on the basis of the winning lottery numbers and thus the next lottery winner will be predicted.
What is your participant role?
Contributor

**Comment by Saurabhbangar0** [comment]
Hello I would like to work on this project. Please assign it to me
Full name :Saurabh Bangar
GitHub Profile Link :https://github.com/Saurabhbangar0
Participant ID (If not, then put NA) : NA
Approach for this Project : I would first perform Data Collection & Processing, Data Analysis then Splitting the data into training data & Test data Handling the Missing values. Then Converting the Category into numeric, build the Model, importing the Test Data and predicting the Values from Models.
What is your participant role? - Contributor

**Comment by deva2412** [comment]
I would like to work on this project. may I work on it???

**Comment by neerazzpatel** [comment]
Full name : Neeraj Patel 
GitHub Profile Link : [https://github.com/neerazzpatel](url)
Participant ID : NA
Approach for this Project : I will try to do it using different algorithms and see which one works best and predicts best.
What is your participant role? : KWOC

**Comment by abhisheks008** [comment]
Issue assigned to you @neerazzpatel

**Comment by abhisheks008** [comment]
Unassigned. **ML-Crate** is going to be part of DWOC from Jan, 15, all the unfinished issues will be taken by the contributors of DWOC.

**Comment by pawaspy** [comment]
Full name : Pawas Pandey
GitHub Profile Link : [https://github.com/pawaspy]
Participant ID : NA
Approach for this Project : Firstly preprocess the data and then perform Exploratory data analysis to perform initial investigation on the provided dataset. The next step would be training the model based on the given dataset, where the model training would be done on the basis of the winning lottery numbers and thus the next lottery winner will be predicted.
What is your participant role?
Contributor

**Comment by abhisheks008** [comment]
Issue assigned to you @pawaspy
