### ISSUE TITLE
Premier League Match Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#178]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Premier League Match Analysis
:red_circle: **Aim** : Analyze the PL matches for the season of 2019-20.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/idoyo92/epl-stats-20192020
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- What is your participant role?
    - [ ] SWOC 2.0 Participant.
    - [ ] JWOC 2022 Participant.
    - [ ] Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by srini047** [comment]
Hi,
I would like to work on this issue.

- **Full Name:** Sriniketh J
- **GitHub Profile Link:** https://github.com/srini047
- **Approach for this Project:** I will initially clean the dataset, preprocess it, and finally do EDA to get insights into the dataset.
- **Participant Role:** 
> - [x] HSOC Participant

**Comment by abhisheks008** [comment]
What's the update on this issue @srini047?

**Comment by srini047** [comment]
> What's the update on this issue @srini047?

@abhisheks008 I have my end-sem exam on Tuesday. I need some time to complete the issue. I will be able to do a PR within Tuesday night at the max. Please consider my issue.

**Comment by abhisheks008** [comment]
It's okay @srini047. Thanks for the update, concentrate on your exams, you can solve this issue later. All the best for your end sem 🚀

**Comment by srini047** [comment]
> It's okay @srini047. Thanks for the update, concentrate on your exams, you can solve this issue later. All the best for your end sem 🚀  

Thanks for the consideration ☺️😊!!

**Comment by abhisheks008** [comment]
Updates please @srini047

**Comment by srini047** [comment]
> Updates please @srini047 

@abhisheks008  I have started the building model's, need to do 2 more models and summary alone.

Sorry for the delay in making PR.

**Comment by abhisheks008** [comment]
Thanks for the update @srini047. No worries, take your time. 😃

**Comment by srini047** [comment]
@abhisheks008 done with Model. Need to make README alone. Will do PR within today.
Sorry for the delay in making PR.
