### ISSUE TITLE
NIFTY Analysis (Jan 22)

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#182]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : NIFTY Analysis (Jan 22)
:red_circle: **Aim** : Analyze the NIFTY Indices of the stock market for the time period of Jan 22.
:red_circle: **Dataset** : https://www.kaggle.com/atrisaxena/nifty-indices-data
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- What is your participant role?
    - [ ] SWOC 2.0 Participant.
    - [ ] JWOC 2022 Participant.
    - [ ] Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avik-creator** [comment]
@abhisheks008 Do we need to do analyse on Nifty 50 only?

**Comment by abhisheks008** [comment]
Analysis and model creation @Avik-creator

**Comment by Avik-creator** [comment]
On nifty 50 only right?

**Comment by abhisheks008** [comment]
Check out the dataset

**Comment by Avik-creator** [comment]
![IMG_20220722_092435.jpg](https://user-images.githubusercontent.com/77090462/180359103-15871ad3-eeaf-404b-b36f-442d8f347c93.jpg)

It has something like this @abhisheks008 so now I need to do analysis on all of them ? Or on nifty 50.

**Comment by abhisheks008** [comment]
Analyse all of them @Avik-creator

**Comment by Avik-creator** [comment]
Please assign me this

**Comment by abhisheks008** [comment]
Will you want to work in this issue @Avik-creator ?

**Comment by Avik-creator** [comment]
Yes

**Comment by Avik-creator** [comment]
@abhisheks008 will it be feasible to do analysis on 6 CSV files?

**Comment by abhisheks008** [comment]
You can analyse them separately (It would be better), or you can merge few of them and then visualize accordingly @Avik-creator 

Issue assigned to you @Avik-creator

**Comment by Avik-creator** [comment]
@abhisheks008 let me see what I can do
