### ISSUE TITLE
Dogecoin INR Data Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#183]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Dogecoin INR Data Analysis
:red_circle: **Aim** : Analyse and predict the price of Dogecoin in the Indian Market and also in INR.
:red_circle: **Dataset** : https://www.kaggle.com/meetnagadia/dogecoin-inr-dataset-20172020
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- What is your participant role?
    - [ ] SWOC 2.0 Participant.
    - [ ] JWOC 2022 Participant.
    - [ ] Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by vickyrules** [comment]
@abhisheks008 assign this, please

**Comment by abhisheks008** [comment]
Can you elaborate your approach please @vickyrules ?

**Comment by abhisheks008** [comment]
@vickyrules are you still interested in this issue, if not then this will be assigned to @Nirvik07.

@Nirvik07 you can check different issues for contribution.

**Comment by vickyrules** [comment]
> Can you elaborate your approach please @vickyrules ?

Analysing  the top 5 features inthe dataset. The details for them are as follows:

Close Price — It is the market close price for currency for that particular day.
High Price — It is highest price of currency for the day.
Low Price — It is the lowest price for currency for that day.
Open Price — It is market open price for currency for that day.
Volume — The volume of currency that is being in trade for that day.

Using regression or segmentation as they are most suited for this type of analysis.

**Comment by vickyrules** [comment]
> @vickyrules are you still interested in this issue, if not then this will be assigned to @Nirvik07.
> 
> @Nirvik07 you can check different issues for contribution.

Yeah I want to work.
And sorry for late reply.

**Comment by abhisheks008** [comment]
No worries, issue assigned to you @vickyrules 

@Nirvik07 you can take up another issue.

**Comment by abhisheks008** [comment]
@vickyrules updates please.

**Comment by vickyrules** [comment]
> @vickyrules updates, please.

I'm busy with college work for the last few days.
And will create a pr by tomorrow evening for sure.

**Comment by abhisheks008** [comment]
No worries, take your time @vickyrules
