### ISSUE TITLE
Predicting Pulsar Star

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#226]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Predicting Pulsar Star
:red_circle: **Aim** : Create a ML model which will predict the pulsar star timing. 
:red_circle: **Dataset** : https://www.kaggle.com/colearninglounge/predicting-pulsar-starintermediate
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- What is your participant role?
    - [ ] SWOC 2.0 Participant.
    - [ ] JWOC 2022 Participant.
    - [ ] Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aka9ksha** [comment]
Hello 👋🏻 ,as Contributor i would like to give my contribution

**Comment by abhisheks008** [comment]
Yeah sure @aka9ksha. Can you elaborate the approach for this project?

**Comment by aka9ksha** [comment]
I'll be using logistic regression as ML model and evaluate it using confusions matrix.

**Comment by abhisheks008** [comment]
Try to use 3-4 different model along with the logistic regression and then compare all the models on the basis of their accuracy scores. Finally, conclude the fact, that which model/algorithm will be best fitted with this dataset.

@aka9ksha Issue assigned to you! Go ahead.

**Comment by abhisheks008** [comment]
Hey, @aka9ksha any progress on this project?

**Comment by aka9ksha** [comment]
I've already completed it ...just having issue in importing kaggle notebook on github repository.
