### ISSUE TITLE
House

### ISSUE THREAD

**Issue by Vanshikagoel0012** [abhisheks008/ML-Crate#24]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** #7 
:red_circle: **Aim** :
:red_circle: **Dataset** :
:red_circle: **Approach** :

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/abhisheks008/ML-Crate/tree/main/Project-Demo-Folder

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Vanshika goel
- GitHub Profile Link :https://github.com/Vanshikagoel0012 
- Participant ID :1093
- Approach for this Project #7 
- Are you a participant of SWOC 2.0?
    YES 

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
@Vanshikagoel0012 I have created the issue "House Price Prediction", go there and comment out with your credentials and approach to get assigned the issue. No need to create a new issue for the same.
