### ISSUE TITLE
Gapminder Colon Cancer

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#247]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Gapminder Colon Cancer
:red_circle: **Aim** : The aim of this project is to predict the Gapminder Colon Cancer from the IARC and WHO dataset given below.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/nancyalaswad90/gapminder-colon-cancer
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Mansikalra104** [comment]
hey @abhisheks008 , I would like to contribute to it

**Comment by Mansikalra104** [comment]
Initially , I would  do Exploratory data analysis, then data preprocessing which we commonly follow for all datasets .As for ML algorithms I would use Decision Trees , Random Forest , Support Vector and logistic regression to check which would be the best and then I can compare different models on the evaluation metrics .

Any suggestion or how can I do it in a better way @abhisheks008 , wholeheartedly invited!

**Comment by abhisheks008** [comment]
Hi @Mansikalra104 it's a nice approach to work on this issue. Are you participating through any open source program?

**Comment by Mansikalra104** [comment]
I am participating through kwoc

**Comment by pawaspy** [comment]
Full name : Pawas Pandey
GitHub Profile Link : github.com/pawaspy
Participant ID (If not, then put NA) : NA
Approach for this Project : I will data clean and preprocess and then use different regression model to predict the cancer percentage.
What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.): JWoC

**Comment by abhisheks008** [comment]
Assigned @pawaspy under JWOC
