### ISSUE TITLE
Bearings Classification

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#252]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Bearings Classification
:red_circle: **Aim** : Aim is to identify the healthy and faulty bearings from the given dataset.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/zlemglsmklkaya/healthy-vs-faulty-bearings
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avik-creator** [comment]
Is this data Analysis? @abhisheks008

**Comment by abhisheks008** [comment]
Nopes, it's basically creating a model which will identify the faulty or, healthy bearings. Before doing that model creation you can analyze and visualize the data as per your choice @Avik-creator

**Comment by Avik-creator** [comment]
So we need to create Linear regression models like?

**Comment by Avik-creator** [comment]
@abhisheks008

**Comment by abhisheks008** [comment]
Yeah, may be some advanced models too!

**Comment by Avik-creator** [comment]
@abhisheks008 like random forest and decision tree?

**Comment by Avik-creator** [comment]
If yes then please assign me

**Comment by abhisheks008** [comment]
Issue assigned to you @Avik-creator

**Comment by jayantp2003** [comment]
Full Name : Jayant Parakh
Github profile : https://github.com/jayantp2003
Participant ID : NA
Approach for this project : Perform exploratory data analysis and use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores.
I wish to participate in KWOC 2022 and would like to contribute to this project.

**Comment by abhisheks008** [comment]
Issue assigned to you @jayantp2003

**Comment by YashSachan2** [comment]
@abhisheks008 Please assign this issue to me under KWOC-23.I plan to compare models like Random Forest,XGBC ,Decision Tress and KNN and then hyperparameter tuning.

**Comment by abhisheks008** [comment]
Issue assigned to you @YashSachan2
