### ISSUE TITLE
Search Interests in Google

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#254]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Search Interests in Google
:red_circle: **Aim** : Analyze the search interests of the users while they use Google.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/mustafaadelibrahim/comparing-search-interest-with-google-trends
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avik-creator** [comment]
@abhisheks008 So we need to just show here which is Top searches? Most Searched person or thing?

**Comment by abhisheks008** [comment]
Yeah it's kind of a Data Analysis and Visualization project, where you need to visualize different aspects and parameters through your data analysis techniques. @Avik-creator

**Comment by abhisheks008** [comment]
Will I assign this issue to you? @Avik-creator

**Comment by Avik-creator** [comment]
Yes please

**Comment by Avik-creator** [comment]
@abhisheks008

**Comment by abhisheks008** [comment]
Issue assigned to you @Avik-creator
