### ISSUE TITLE
Disease Prediction

### ISSUE THREAD

**Issue by vickyrules** [abhisheks008/ML-Crate#256]
### ML-Crate Repository (Proposing new issue)
:red_circle: Disease prediction model with GUI (Machine Learning) :
:red_circle: predicting diseases from the symptoms provided by the user :
:red_circle: **Approach** : 
Using - Random Forest, descision tree and naive bayes.

Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by vickyrules** [comment]
@abhisheks008 please assign this to me.

**Comment by abhisheks008** [comment]
Can you elaborate me the project? @vickyrules

**Comment by vickyrules** [comment]
@abhisheks008
Model will predict the disease (like typhoid, malaria and food poisoning etc.) based on the symptoms user provide.

**Comment by abhisheks008** [comment]
Can you share me the dataset? @vickyrules

**Comment by abhisheks008** [comment]
@vickyrules you are going to create a GUI for the user interaction. Then add your front end files in the separate folder and name it as `GUI`, also provide the deploy link in the main README.md file.

**Comment by vickyrules** [comment]
@abhisheks008 
https://github.com/vickyrules/DisesesPredictor
Here the project i have completed it few months back.

**Comment by abhisheks008** [comment]
Yeah go for it. You have already developed it! It was nice presentation btw! Issue assigned to you @vickyrules

**Comment by abhisheks008** [comment]
@vickyrules You have used three algorithms for the predictions, can you use 2 more algorithms and then compare them altogether to find the best fitted one. My suggestion will be, Support Vector Machine and XgBoost Classifier, you can choose yours!

**Comment by vickyrules** [comment]
@abhisheks008  i will try

**Comment by abhisheks008** [comment]
@vickyrules have you filled up the Contact information form, given in the ML-Crate announcement channel of the HSoC discord server? I am not able find out your contact details. Please ensure that you must fill that form before pushing your PR.

Thanks and regards!

**Comment by vickyrules** [comment]
> @vickyrules have you filled up the Contact information form, given in the ML-Crate announcement channel of the HSoC discord server? I am not able find out your contact details. Please ensure that you must fill that form before pushing your PR.
> 
> Thanks and regards!

Done 👍

**Comment by abhisheks008** [comment]
> > @vickyrules have you filled up the Contact information form, given in the ML-Crate announcement channel of the HSoC discord server? I am not able find out your contact details. Please ensure that you must fill that form before pushing your PR.
> > Thanks and regards!
> 
> Done 👍

Thanks man!
