### ISSUE TITLE
FIDE Chess Ranking Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#271]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : FIDE Chess Ranking Analysis
:red_circle: **Aim** : Analyze the dataset with different parameters.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/surajjha101/fide-chess-rankings-updated
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by GundaSudarrshan** [comment]
@abhisheks008  What exactly we need to predict here 
I think we just need to do EDA and draw different Inferences from the dataset 
I don't see any use of applying ML algorithms here because what exactly we should predict here
the positions can't be predicted and rating can also can't be predicted i feel


can you explain this once!!!!

**Comment by abhisheks008** [comment]
Yeah, this is a Data Analysis and visualization project, where you need to analyze different parameters and provide a bunch of conclusions at the end of the project. You can check other data analysis projects of ML-Crate for more clarification on how the things should be presented. And if you wanna work on specifically on a prediction/classification model oriented project, then you can check other issues. There are lots of issues on this.

@GundaSudarrshan

**Comment by Nirvik07** [comment]
Full name : NIRVIK GHOSH
GitHub Profile Link : @Nirvik07 
Participant ID (If not, then put NA) : NA
Approach for this Project : To analyse various chess players around the world. 
What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)
HRSoC 2022 Participant.

**Comment by abhisheks008** [comment]
@GundaSudarrshan are you willing to contribute in this issue, otherwise I'll assign this to @Nirvik07

**Comment by Nirvik07** [comment]
@abhisheks008 could you hold this project for me if  @GundaSudarrshan does want to work in it. Meanwhile I can work on another issue and finish it up and later on take this issue up. is ok for you? @abhisheks008

**Comment by abhisheks008** [comment]
Yeah sure @Nirvik07

**Comment by GundaSudarrshan** [comment]
yes @abhisheks008  I wanted to Work on this Issue

**Comment by GundaSudarrshan** [comment]
Full name : Gunda Sudarrshan
GitHub Profile Link : https://github.com/GundaSudarrshan
Participant ID (If not, then put NA) : NA
Approach for this Project : Analyzing about top chess players in the World by using  Exploratory Data Analysis.
What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)
HRSoC 2022 Participant.

**Comment by abhisheks008** [comment]
Issue assigned to you @GundaSudarrshan

**Comment by abhisheks008** [comment]
Updates please @GundaSudarrshan

**Comment by GundaSudarrshan** [comment]
@abhisheks008  sorry for the Delay , I was having My end semester Exams so I was Unable to Contribute much, I will try to update by weekend , If that's not ok for you can reassign to someone.

**Comment by abhisheks008** [comment]
Don't worry. Concentrate in your end sem exams, you can complete it later on @GundaSudarrshan

**Comment by abhisheks008** [comment]
Weekend is coming up! How's all going with your exams? @GundaSudarrshan

**Comment by GundaSudarrshan** [comment]
@abhisheks008  I think you can assign this to someone else, I have exams till 8th august ,I will be free from that day

**Comment by abhisheks008** [comment]
As you wish. All the best for your exams @GundaSudarrshan

**Comment by Nirvik07** [comment]
@abhisheks008 can you assign me this?

**Comment by abhisheks008** [comment]
Issue assigned to you @Nirvik07
