### ISSUE TITLE
Global Retailers Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#278]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Global Retailers Analysis
:red_circle: **Aim** : Analyse the global retailers using different aspects.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/dhimananubhav/global-top-250-retailers
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by snehal1024** [comment]
Hello I would like to work on this project. Please assign it to me
Full name : Yevale Snehal Dilip
GitHub Profile Link : https://github.com/snehal1024
Participant ID (If not, then put NA) : NA
Approach for this Project : I would first try 3-4 algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. 
What is your participant role? - Contributor

**Comment by abhisheks008** [comment]
Issue assigned to you @snehal1024

**Comment by chandana62** [comment]
Full name : Chandana sri
GitHub Profile Link : https://github.com/chandana62
Participant ID (If not, then put NA) : NA
Approach for this Project : I would first try 3-4 algorithms to find out the best fitted algorithm for the model by checking the accuracy scores.
What is your participant role? - Contributor
Please assign me this issue

**Comment by chandana62** [comment]
I would like to give a try on this project. Please assign it to me

**Comment by abhisheks008** [comment]
Issue assigned to you @chandana62

**Comment by abhisheks008** [comment]
Unassigned. **ML-Crate** is going to be part of DWOC from Jan, 15, all the unfinished issues will be taken by the contributors of DWOC.

**Comment by mariam7084** [comment]
Hi !! @abhisheks008 
I would like to take this issue.

Full name : Mariam
GitHub Profile Link : https://github.com/mariam7084
Participant ID (If not, then put NA) : NA
Approach for this Project : perform EDA and visualization to find insights in data
What is your participant role? JWoC 2024

**Comment by abhisheks008** [comment]
Assigned @mariam7084
