### ISSUE TITLE
Heart Failure Prediction

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#295]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Heart Failure Prediction
:red_circle: **Aim** : Create a prediction model for heart failure of the patients.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/asgharalikhan/mortality-rate-heart-patient-pakistan-hospital
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avik-creator** [comment]
Please assign me this. @abhisheks008

**Comment by abhisheks008** [comment]
Issue assigned to you @Avik-creator

**Comment by Avik-creator** [comment]
Sorry but can't do it for now. Will do it later @abhisheks008

**Comment by Sugam-Mahajan** [comment]
Please assign me this. @abhisheks008

**Comment by abhisheks008** [comment]
Are you a participant from any open source program or, just wanna contribute here as a contributor?
@Sugam-Mahajan

**Comment by Sugam-Mahajan** [comment]
Just wanted to contribute as a part of our college project

**Comment by abhisheks008** [comment]
Sounds great @Sugam-Mahajan. Can you elaborate the approach you wanna go through while solving this issue?

**Comment by Sugam-Mahajan** [comment]
We will use apply EDA and then apply 3 algo namely: KNeighboursClassifier, DecisionTreeClasssifier, RandomForestClassifier . Then compare the accuracy of each algorithm.

**Comment by Brijesh003** [comment]
Full name : BrijeshMali
GitHub Profile Link : https://github.com/Brijesh003
Participant ID (If not, then put NA) : NA
Approach for this Project : I will use RandomForest & KNeighbours

**Comment by Brijesh003** [comment]
I'm new to ML so I will learn and contribute

**Comment by abhisheks008** [comment]
@Sugam-Mahajan your approach sounds good to me. This issue is assigned to you. Go ahead!

@Brijesh003 we assign issues on first come first serve basis, as @Sugam-Mahajan commented here first with the approach, I have to assign that. You can take up other issues and comment on them with your approach.

**Comment by Brijesh003** [comment]
Ok Sir

**Comment by abhisheks008** [comment]
Hey @Brijesh003 updates regarding this issue.

**Comment by Brijesh003** [comment]
Hey @abhisheks008 you have assigned this issue to @Sugam-Mahajan.

**Comment by abhisheks008** [comment]
My bad @Brijesh003. Sorry for the inconvenience caused.

@Sugam-Mahajan updates regarding this issue.

**Comment by Sugam-Mahajan** [comment]
Hi @abhisheks008, I have successfully implemented one algorithm along with EDA. I will complete this till Saturday with the remaining 2 algorithms.

Thank you

**Comment by Sugam-Mahajan** [comment]
Hey @abhisheks008 can you please check our folders'
