### ISSUE TITLE
Commonwealth Games Tweets Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#350]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Commonwealth Games Tweets Analysis
:red_circle: **Aim** : Analyse the tweets of the commonwealth games 2022.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/aneeshtickoo/tweets-on-common-wealth-games-2022
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by prasad669** [comment]
Full name : Prasad Choudhari
GitHub Profile Link : https://github.com/prasad669
Participant ID (If not, then put NA) : NA
Approach for this Project : I would Like to contribute for this project 
I will try to use different Algorithms with great accuracy to Analyze the Results

**Comment by abhisheks008** [comment]
Issue assigned to you @prasad669.

**Comment by abhisheks008** [comment]
Issue has been un-assigned from you due to inactivity.
@prasad669

**Comment by sakshipratap** [comment]
I would like to contribute to this project.

Full name : Sakshi Pratap
GitHub Profile Link : https://github.com/sakshipratap
Participant ID (If not, then put NA) : NA
Approach for this Project : I'll thoroughly analyze the data by plotting multiple graphs, bar graphs and performing multiple data analysis techniques. 
What is your participant role? KWoC'22

**Comment by abhisheks008** [comment]
Issue assigned to you @sakshipratap

**Comment by abhisheks008** [comment]
Unassigned. **ML-Crate** is going to be part of DWOC from Jan, 15, all the unfinished issues will be taken by the contributors of DWOC.

**Comment by adi271001** [comment]
can you please assign this to me under kwoc

**Comment by abhisheks008** [comment]
Finish the previous work first.

**Comment by adi271001** [comment]
done , now can you please assign it

**Comment by abhisheks008** [comment]
Assigned.
