### ISSUE TITLE
Stock News Sentiment Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#351]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Stock News Sentiment Analysis
:red_circle: **Aim** : Analysis of the news of the stock market.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/avisheksood/stock-news-sentiment-analysismassive-dataset
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ImArrow117** [comment]
Hello I would like to work on this project. Please assign it to me
Full Name: Abhishek Mhatre 
GitHub Link: https://github.com/ImArrow117
Participant ID: NA
Approach For this project: I will try to use 2-4 algorithms to implement the models and compare all the algorithms to find out the best fitting algorithm for the model by checking the accuracy scores. Also, I will perform an exploratory data analysis before creating any model.
What is your participant role: contributor

**Comment by abhisheks008** [comment]
Issue assigned to you @ImArrow117

**Comment by abhisheks008** [comment]
Issue has been un-assigned from you due to inactivity.
@ImArrow117

**Comment by Nachiket-Kathoke** [comment]
Hello Abhishek, I have implemented ML algorithms like Logistic regression, NB and OCSVM.
This is the link of the folder containing the notebook and images of the confusion matrix and ROC curves.
https://drive.google.com/drive/folders/1Pln252JgyrInvhxEbjbusUW0FJyiF6tk?usp=share_link
Further, I would like to implement transformer-based models for better accuracy.
Kindly consider it for mid-evals

**Comment by abhisheks008** [comment]
Unassigned. **ML-Crate** is going to be part of DWOC from Jan, 15, all the unfinished issues will be taken by the contributors of DWOC.

**Comment by Shobhit-Bandhu** [comment]
Full name : Shobhit Bandhu
GitHub Profile Link : https://github.com/Shobhit-Bandhu
Participant ID (If not, then put NA) : NA
Approach for this Project : 
- Preprocessing (Balance dataset for both outputs)
- EDA (Message Length, punctuations etc.)
- Data prep (Vectorize text)
- Classification model (Random Forest Classifier, SVM, RNNs, Hugging Face models...etc)

What is your participant role? Contributor

**Comment by abhisheks008** [comment]
Issue assigned to you @Shobhit-Bandhu

**Comment by abhisheks008** [comment]
Hi @Shobhit-Bandhu can you please share your email ID with me on Discord for further communications?
