### ISSUE TITLE
Pima Indians Diabetes Prediction

### ISSUE THREAD

**Issue by divya-gupta12** [abhisheks008/ML-Crate#36]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Pima Indians Diabetes Prediction
:red_circle: **Aim** : To predict whether a person is diabetic or not.
:red_circle: **Dataset** : https://www.kaggle.com/uciml/pima-indians-diabetes-database
:red_circle: **Approach** : Full model building process to be explained from Exploratory data analysis to evaluation metrics.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/abhisheks008/ML-Crate/tree/main/Project-Demo-Folder

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- Are you a participant of SWOC 2.0?
    - [ ] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by divya-gupta12** [comment]
- Full name : Divya Shanker Gupta
- GitHub Profile Link : https://github.com/divya-gupta12
- Participant ID : 1155
- Approach for this Project : I will Implement Logistic Regression model to do this and then to increase its performance will try Random Forest Classifier .
- Are you a participant of SWOC 2.0?
   YES
 I want to work on this issue

**Comment by ASLManasa** [comment]
@divya-gupta12 assigning you . Try to complete it within 3 days with proper format.
