### ISSUE TITLE
Startups Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#393]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Startups Analysis
:red_circle: **Aim** : The aim of this project is to create a data analysis model which will analyze the startups' data.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/thedevastator/startups-valued-at-1-billion-or-more
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Khushi260** [comment]
Full name : Khushi Jha
GitHub Profile Link : https://github.com/Khushi260
Participant ID (If not, then put NA) : NA
Approach for this Project : At first I will explore dataset using various tools provided by the libraries
What is your participant role? KWOC'22

**Comment by aditya0402-debug** [comment]
Full name : Aditya Yash Raj
GitHub Profile Link : https://github.com/aditya0402-debug
Participant ID (If not, then put NA) : NA
Approach for this Project : EDA ...then analysing in 3-4 algorithms
What is your participant role? KWOC'22 contributor

**Comment by sanchitgarg2204** [comment]
Full name : Sanchit Garg
GitHub Profile Link :
Participant ID (If not, then put NA) :
Approach for this Project : Using sklearn and pandas, I will apply 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. I will also do an exploratory data analysis before creating any model, using cufflinks and plotly.
What is your participant role? Kwoc'22 Contributor
Please assign this issue to me.

**Comment by abhisheks008** [comment]
Issue assigned to you @Khushi260

**Comment by abhisheks008** [comment]
Unassigned. **ML-Crate** is going to be part of DWOC from Jan, 15, all the unfinished issues will be taken by the contributors of DWOC.

**Comment by ellow0rld** [comment]
Full name : Madhu Shree Aravindan
GitHub Profile Link : https://github.com/ellow0rld
Participant ID (If not, then put NA) : NA
Approach for this Project : Will clean the dataset. And will analyze the data and provide visualization through different plotting libraries.
What is your participant role? KWOC'23

**Comment by abhisheks008** [comment]
Issue assigned to you @ellow0rld
