### ISSUE TITLE
Eurovision Song Contest Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#396]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Eurovision Song Contest Analysis
:red_circle: **Aim** : Create a data analysis project which will analyse the data given in the dataset.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/latifahmakuyi/eurovision-winners-1956-2022
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ManasviEmmadi** [comment]
Hi! I would like to contribute to this under KWOC '22.
Full Name: Manasvi Emmadi
GitHub Profile Link: https://github.com/ManasviEmmadi
Participant ID: NA
Approach for this Project : Use different eda techniques to observe patterns to understand dataset
What is your participant role?: KWoC '22

**Comment by abhisheks008** [comment]
Issue assigned to you @ManasviEmmadi

**Comment by abhisheks008** [comment]
Unassigned. **ML-Crate** is going to be part of DWOC from Jan, 15, all the unfinished issues will be taken by the contributors of DWOC.

**Comment by mariam7084** [comment]
Hi!
I'm interested in taking this issue.

Full Name : Mariam
GitHub Profile Link : https://github.com/mariam7084
Participant ID: NA
Approach for this Project : Firstly, i will perform exploratory data analysis to understand the various trends in data. Then I will start modeling process using different models and evaluate them using suitable metrics and choose the best model out of them.
What is your participant role? KWoC

**Comment by abhisheks008** [comment]
Hi @mariam7084 issue assigned to you. You can start working on it.
