### ISSUE TITLE
Mall Customers Segmentation

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#4]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Mall Customers Segmentation
:red_circle: **Aim** : To classify different customers.
:red_circle: **Dataset** : https://www.kaggle.com/shwetabh123/mall-customers
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/abhisheks008/ML-Crate/tree/main/Project-Demo-Folder

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- Are you a participant of SWOC 2.0?
    - [ ] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by suyogkokaje** [comment]
Full name : Suyog Kokaje
GitHub Profile Link : https://github.com/suyogkokaje
Participant ID : 1032
Approach for this Project : K-means clustering
Are you a participant of SWOC 2.0?
YES

**Comment by abhisheks008** [comment]
@suyogkokaje Implement 3-4 Algorithms for creating the model, then check the accuracy scores of them and finalize the best fitted algorithm/model for this project.

Anyways this issue is assigned to you.

**Comment by abhisheks008** [comment]
What's the update here @suyogkokaje

**Comment by suyogkokaje** [comment]
Sorry for inconvenience. But my written and practical exams are going on in college. So I am unable to work on this issue. You can unassign me 😓 if anyone else is interested in working on this issue. Sorry again.

**Comment by abhisheks008** [comment]
You can start working on it after your sem is over, if you wish @suyogkokaje

**Comment by abhisheks008** [comment]
@suyogkokaje have you done with your exams?

**Comment by suyogkokaje** [comment]
Yup @abhisheks008  my exams are finished. I have started working. Will make PR within a week. Is it okay? 😅

**Comment by abhisheks008** [comment]
Yup that's fine @suyogkokaje

**Comment by abhisheks008** [comment]
Hey @suyogkokaje what's the update here. You've asked for a week and I have provided that time. Now you are running out of time.

**Comment by tandrimasingha** [comment]
Sir I want to work on this issue. 

Full name: Tandrima Singha
GitHub Profile Link: https://github.com/tandrimasingha
Participant ID: 1044
Approach for this Project: Using unsupervised learning algorithms We have to segment customers and classify them. Perform EDA
Are you a participant of SWOC 2.0?
YES

**Comment by abhisheks008** [comment]
@tandrimasingha are you willing to solve this issue?

**Comment by tandrimasingha** [comment]
Yes sir 
I want to do this

**Comment by abhisheks008** [comment]
Great then, this issue is assigned to you. @tandrimasingha
