### ISSUE TITLE
Blood Donation Analysis

### ISSUE THREAD

**Issue by Anuragwagh** [abhisheks008/ML-Crate#438]
**Project Name:** Blood Donation Analysis

**Aim:** Create a model that can accurately predict which donors are likely to donate blood again. 

**Dataset:** https://www.kaggle.com/code/mmmarchetti/predicting-blood-donations

**Approach:** Try to focus on atleast 3-4 machine learning models and 1-2 deep learninf methods for a better comparison and better outcome. Here are the models you can try out,
1. Random Forest
2. Decision Tree
3. SVM
4. XgBoost
5. Gradient Boosting
6. Logistic Regression
7. MLP Classifier
8. Lasso Regression
9. Ridge Regression

**Open Source Event:** IWOC 2024

**Comment by abhisheks008** [comment]
Need more information about the issue. Follow the issue template for the same.

**Comment by shubhammore45** [comment]
Please assign this issue to me

**Comment by Minato96** [comment]
Can I get this assigned for me? I am from Kwoc and joined in the discord too with username minato96

**Comment by hemant933** [comment]
sir , assign it to me

**Comment by abhisheks008** [comment]
Can you share the approach and the dataset url, you want to work with?
@hemant933

**Comment by hemant933** [comment]
https://www.kaggle.com/code/mmmarchetti/predicting-blood-donations - dataset
as for approach i will use random forest or gradient boosting modals

**Comment by abhisheks008** [comment]
The dataset is well and good. Try to focus on atleast 3-4 machine learning models and 1-2 deep learninf methods for a better comparison and better outcome. Here are the models you can try out,
1. Random Forest
2. Decision Tree
3. SVM
4. XgBoost
5. Gradient Boosting
6. Logistic Regression
7. MLP Classifier
8. Lasso Regression
9. Ridge Regression

Issue assigned to you @hemant933
