### ISSUE TITLE
Automobile Sales Data Analysis and Prediction

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#440]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Automobile Sales Data Analysis and Prediction
:red_circle: **Aim** : The aim of this project is to create a machine learning model to predict the sales of the automobiles and prepare a data analysis of the same.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/ddosad/auto-sales-data
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ankana2113** [comment]
Full name : Ankana Pari
GitHub Profile Link : https://github.com/ankana2113
Participant ID (If not, then put NA) : couldn't find
Approach for this Project : Would plot some graphs to determine the trend of the data and then try to approach which ml model fits best for e.g, regression or random regression etc.
What is your participant role?KWoC

**Comment by ankana2113** [comment]
I am facing a problem on how to convert datetime obj into a string because
standardizing using StandardScaler requires a string. Can you please help
me out?
Ankana
Issue #440

**Comment by abhisheks008** [comment]
Can you share the problem in detail. You can connect with me in Discord.

**Comment by abhisheks008** [comment]
Issue assigned to you @Mudassir-A

**Comment by why-aditi** [comment]
Aditi Kala
Github:- https://github.com/why-aditi
Participation ID:- NA
Approach: Clean and preprocess the data, handling missing values and ensuring all variables are in suitable formats. Conduct exploratory data analysis to understand relationships and patterns in the data. Select relevant features that influence sales, possibly using feature engineering techniques. Choose appropriate regression algorithms like Random Forest or Gradient Boosting, train the model on a portion of the data, and evaluate its performance using metrics such as MSE. Interpret the model's results to extract insights into key drivers of sales, such as the impact of car features or economic conditions. Visualize actual versus predicted sales values to assess model accuracy. 
Participation Role:- SSOC Season 3

**Comment by abhisheks008** [comment]
> Aditi Kala Github:- https://github.com/why-aditi Participation ID:- NA Approach: Clean and preprocess the data, handling missing values and ensuring all variables are in suitable formats. Conduct exploratory data analysis to understand relationships and patterns in the data. Select relevant features that influence sales, possibly using feature engineering techniques. Choose appropriate regression algorithms like Random Forest or Gradient Boosting, train the model on a portion of the data, and evaluate its performance using metrics such as MSE. Interpret the model's results to extract insights into key drivers of sales, such as the impact of car features or economic conditions. Visualize actual versus predicted sales values to assess model accuracy. Participation Role:- SSOC Season 3

Implement 5-6 models for this project.

Assigned @why-aditi
