### ISSUE TITLE
Reddit Comments Analysis during CWC Final 2023

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#443]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Reddit Comments Analysis during CWC Final 2023
:red_circle: **Aim** : Create an analysis for model the Reddit Comments made during CWC Final 2023.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/hitman69/reddit-comments-60k-ind-vs-aus-wc-final
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by p1utoze** [comment]
Full name : Adithya Awati
GitHub Profile Link : [p1utoze](https://github.com/p1utoze)
Participant ID (If not, then put NA) : NA
Approach for this Project : Perform EDA and sentiment analysis. Try to use LGBM, CatBoost, etc.
What is your participant role? KWOC 23

**Comment by abhisheks008** [comment]
Try to implement more than 4-5 models for this issue and check the best fitted model using the accuracy scores. Issue assigned to you. All the best and go ahead!
@p1utoze

**Comment by p1utoze** [comment]
Hello @abhisheks008 I am working on this issue. I'll be creating a PR by this week.

**Comment by abhisheks008** [comment]
Thanks for the update. Keep going!
