### ISSUE TITLE
House Rent Analysis and Prediction of Mumbai

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#444]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : House Rent Analysis and Prediction of Mumbai
:red_circle: **Aim** : Create a ML model for analyzing and predicting the house rents of Mumbai based on the given dataset.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/lokeshgupta2020/house-rent-in-mumbai
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ankana2113** [comment]
@abhisheks008 can I work on this issue?

**Comment by abhisheks008** [comment]
Can you share your approach for solving this issue?
@ankana2113

**Comment by Cgarg9** [comment]
can I be assigned this issue?

**Comment by abhisheks008** [comment]
@Cgarg9 please share your approach for solving this issue.

**Comment by Cgarg9** [comment]
Full name : Chirag Garg
GitHub Profile Link : https://github.com/Cgarg9
Participant ID (If not, then put NA) :
Approach for this Project : Would plot few graphs to visualise the data trends. Then would try different algorithms like linear regression, random forest, XGBoost.
What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.) KWOC

**Comment by abhisheks008** [comment]
Don't worry about the participant ID, it's of no use in KWOC. Anyways it's a nice approach for this issue. Issue assigned to you. You can start working on it.
@Cgarg9

**Comment by abhisheks008** [comment]
Hi @Cgarg9 any update on this issue?

**Comment by Cgarg9** [comment]
Almost done with this. Will make the pr by Saturday

**Comment by Avdhesh-Varshney** [comment]
@abhisheks008 i would like to work on this issue. Could you please assign it to me?

Full name : Avdhesh Varshney
GitHub Profile Link : https://github.com/Avdhesh-Varshney
Participant ID (If not, then put NA) :
Approach for this Project : 
- Analysing the dataset.
- EDA processing.
- Filtering the dataset so that which can easily fit into any type of the model.
- Applying the different type of the algorithms like, random forest, linear regression, xgboost, knn classifier, svm classifier, etc.
- Summarizing all the algorithms at the end of the notebook.

What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.) KWOC

**Comment by Avdhesh-Varshney** [comment]
@abhisheks008 please assign this project to me to contribute under KWOC'23

**Comment by abhisheks008** [comment]
Hi @Avdhesh-Varshney this is already assigned to someone.

**Comment by raysofani** [comment]
Hi @abhisheks008 , I would like to take up this issue!!
Full name : Aniket Ray
GitHub Profile Link : https://github.com/raysofani
Participant ID (If not, then put NA) : NA
Approach for this Project : 
1. EDA Processing
2. Feature engineering
3. Use 3-4 algorithm to Analyse and do the required Prediction.
What is your participant role? IWOC 2.0

**Comment by abhisheks008** [comment]
Can you share the models you want to implement for this project?

**Comment by pranjalipilankar** [comment]
Full name: Pranjali Pilankar
GitHub Profile Link: https://github.com/pranjalipilankar
Participant ID (If not, then put NA) : 
Approach for this Project: 
1) Preprocessing the data to remove outliers and reduce dimensions by PCA
2) Plotting data using Matplotlib to identify distinct trends and also make assessments regarding the suitable model to apply
3) Apply algorithms like linear regression, polynomial regression, and random forest algorithms. Also, explore other algorithms which may be suitable according to the distribution of the data
4) Analyse the accuracy of the models using RMSE error and also explore other methods.
What is your participant role?: JWOC '24

**Comment by pranjalipilankar** [comment]
@abhisheks008  Please assign this issue to me under JWOC'24  :)

**Comment by abhisheks008** [comment]
> @abhisheks008 Please assign this issue to me under JWOC'24 :)

This issue is part of IWOC2024.

**Comment by raysofani** [comment]
> Can you share the models you want to implement for this project?

Will use common ones like Linear regression, decision tree, random forest and support vector machine. Will also apply Gradient boosting that may offer improved accuracy. Further the choice of model will depend on the complexity  of the dataset , which we can come upon once analysing the dataset.

**Comment by raysofani** [comment]
@abhisheks008 Please assign this issue to me under IWOC2024

**Comment by pawaspy** [comment]
Full name : Pawas Pandey
GitHub Profile Link : github.com/pawaspy
Participant ID (If not, then put NA) : NA
Approach for this Project : Linear regression, decision tree, random forest and support vector machine. Will also apply Gradient boosting that may offer improved accuracy. Further the choice of model will depend on the complexity of the dataset , which we can come upon once analysing the dataset.
What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.) : IWoC

@abhisheks008 please assign me the issue.

**Comment by pranjalipilankar** [comment]
Sorry for the typo mistake. I want to work on this issue as a part of IWOC '24.

**Comment by bhavya-06darshnik** [comment]
Full name : Bhavya Kumar
GitHub Profile Link : https://github.com/bhavya-06darshnik
Participant ID (If not, then put NA) : NA
- Approach for this Project : I'll use basics of ML, such as preprocessing data, plotting graph using matplotlib & will use common algo like Linear regression, polynomial regression, & will analyse data.
-  What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

@abhisheks008  please assign me this issue as IWOC2024

**Comment by aamiransari072** [comment]
Full name : Md Aamir Ansari 
GitHub Profile Link : https://github.com/aamiransari072
Participant ID  :NA
Approach for this Project : we first do the eda on data set trying to figure out the insides of data set then we apply diffrent diffrent algorithms like linear regression , svm, decison tree and deep learning then we evaluate our model according to roc curve and mae 
What is your participant role? IWOC 2.O

**Comment by abhisheks008** [comment]
Issue assigned to @raysofani on FCFS basis. Those who have commented apart from @raysofani, you can check out other issues present in this repo (check out the page 2 of the Issues section, lots of open issues are present there to work on).
