### ISSUE TITLE
Emotion Recognition in Text

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#461]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Emotion Recognition in Text
:red_circle: **Aim** : Develop a model that can analyze text data and classify the emotions expressed (e.g., happiness, sadness, anger).
:red_circle: **Dataset** : http://multicomp.cs.cmu.edu/resources/emoreact-dataset/
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by SRUJANA2199** [comment]
Full name :A.Sai Srujana
GitHub Profile Link :https://github.com/SRUJANA219
Participant ID (If not, then put NA) :
Approach for this Project :using 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores, doing a exploratory data analysis before creating any model.
What is your participant role? kwoc

**Comment by abhisheks008** [comment]
I can't assign issues on a deadline day, I believe developing a whole ML project is not a task of 12 hours. It needs to be reviewed and then the PR will merge. There is lots of possibility that this will not work on a deadline day.

If you want to contribute in this repository, you can register for JWOC or, IWOC. In both these events ML-Crate is going to participate. You can check out their websites for the registration.

**Comment by SRUJANA2199** [comment]
Full name :A.Sai Srujana
GitHub Profile Link :https://github.com/SRUJANA219
Participant ID (If not, then put NA) :
Approach for this Project :using 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores, doing a exploratory data analysis before creating any model.
What is your participant role? iwoc

**Comment by SRUJANA2199** [comment]
can you please assign me this?

**Comment by abhisheks008** [comment]
Extremely sorry for the late reply @SRUJANA2199. As the deadline of the program is today midnight, can you push the pull request before that?

**Comment by SRUJANA2199** [comment]
i will try

**Comment by SRUJANA2199** [comment]
if i cant would you assign me under different winter of code if possible?

**Comment by abhisheks008** [comment]
Are you part of JWOC? @SRUJANA2199

**Comment by SRUJANA2199** [comment]
yes.

**Comment by abhisheks008** [comment]
Cool then I am assigning this issue to you under JWOC 2024 @SRUJANA2199

**Comment by SRUJANA2199** [comment]
Also the dataset link which you have provided has no datasets it has only references and abstract of publications.Kindly suggest me how to go about

**Comment by abhisheks008** [comment]
On the left side of the page you'll get the dataset links, find out the dataset which is complied with the issue name. If you are unable to find the dataset, do let me know, I'll find it for you.

**Comment by abhisheks008** [comment]
You can use this one, https://www.kaggle.com/datasets/pashupatigupta/emotion-detection-from-text, in case you face difficulty while finding the dataset.

**Comment by SRUJANA2199** [comment]
ok will use this
