### ISSUE TITLE
Google Devices Q and A Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#464]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Google Devices Q and A Analysis
:red_circle: **Aim** : Create a bunch of ML models to analyze the Google Devices Q and A dataset.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/aashidutt3/google-devices-q-and-a-dataset
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by SRUJANA2199** [comment]
Full name :A.Sai Srujana
GitHub Profile Link :https://github.com/SRUJANA219
Participant ID (If not, then put NA) :
Approach for this Project :using 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores, doing a exploratory data analysis before creating any model.
What is your participant role? kwoc

**Comment by abhisheks008** [comment]
I can't assign issues on a deadline day, I believe developing a whole ML project is not a task of 12 hours. It needs to be reviewed and then the PR will merge. There is lots of possibility that this will not work on a deadline day.

If you want to contribute in this repository, you can register for JWOC or, IWOC. In both these events ML-Crate is going to participate. You can check out their websites for the registration.

**Comment by SRUJANA2199** [comment]
Full name :A.Sai Srujana
GitHub Profile Link :https://github.com/SRUJANA219
Participant ID (If not, then put NA) :
Approach for this Project :using 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores, doing a exploratory data analysis before creating any model.
What is your participant role? jwoc

**Comment by abhisheks008** [comment]
@SaiSravanthiChandana and @SRUJANA2199 wait for the program to start officially.

**Comment by abhisheks008** [comment]
Implement the following models for this project,
1. Random forest
2. Decision tree
3. Logistic regression
4. Lasso
5. Ridge
6. Gradient boosting
7. XgBoost
8. MLP

Check the accuracy scores of the deployed models and find out the best one based on the best accuracy score.

Are you able to do this? @SaiSravanthiChandana

**Comment by CoderOMaster** [comment]
@abhisheks008 can you please assign this issue to me under JWOC 24?
i will impliment all these algos..

Regards.

**Comment by CoderOMaster** [comment]
@abhisheks008 please assign this to me

**Comment by CoderOMaster** [comment]
> Implement the following models for this project,
> 
> 1. Random forest
> 2. Decision tree
> 3. Logistic regression
> 4. Lasso
> 5. Ridge
> 6. Gradient boosting
> 7. XgBoost
> 8. MLP
> 
> Check the accuracy scores of the deployed models and find out the best one based on the best accuracy score.
> 
> Are you able to do this? @SaiSravanthiChandana

hey as this is nlp based classifier model,
may i use transfer learning models to implement?

**Comment by abhisheks008** [comment]
> > Implement the following models for this project,
> > 
> > 1. Random forest
> > 2. Decision tree
> > 3. Logistic regression
> > 4. Lasso
> > 5. Ridge
> > 6. Gradient boosting
> > 7. XgBoost
> > 8. MLP
> > 
> > Check the accuracy scores of the deployed models and find out the best one based on the best accuracy score.
> > Are you able to do this? @SaiSravanthiChandana
> 
> hey as this is nlp based classifier model, may i use transfer learning models to implement?

Yes you can. Do you want to work on this issue?

**Comment by CoderOMaster** [comment]
Yes sir absolutely.Please assign this to me

**Comment by abhisheks008** [comment]
Assigned @CoderOMaster
