### ISSUE TITLE
The Simpsons Episodes Dataset Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#465]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : The Simpsons Episodes Dataset Analysis
:red_circle: **Aim** : Create a bunch of ML models to analyze the Simpsons Episodes Dataset
:red_circle: **Dataset** : https://www.kaggle.com/datasets/thedevastator/the-simpsons-episodes-dataset
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Bayyana-kiran** [comment]
Full name : SAI KIRAN B L S
GitHub Profile Link : https://github.com/Bayyana-kiran
Participant ID (If not, then put NA) : NA
Approach for this Project : I plan to start by conducting exploratory data analysis to understand the distribution of episodes across seasons and series. I will then implement machine learning models to analyze viewer engagement and explore temporal trends in IMDb ratings. My goal is to uncover patterns and insights related to specific episodes, characters, and viewer interactions.
What is your participant role : IWOC2024 

CAN U ASSIGN ME FOR THIS ISSUE?

**Comment by abhisheks008** [comment]
Issue assigned to you @Bayyana-kiran

**Comment by Bayyana-kiran** [comment]
hello @abhisheks008 , as the title say "The Simpsons Episodes Dataset Analysis"  should i visualize the data or should also make ml model regarding it ,if yes then what are inputs?

**Comment by abhisheks008** [comment]
@Bayyana-kiran use the dataset given above. If you cam do model implementation along with the EDA, go ahead, that will carry extra points for you.

**Comment by Bayyana-kiran** [comment]
Oh okay tq @abhisheks008 I'm working on it.

**Comment by Bayyana-kiran** [comment]
hello @abhisheks008 kindly please check
