### ISSUE TITLE
Mineral Classification

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#467]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Mineral Classification
:red_circle: **Aim** : Create a bunch of ML models to classify the minerals.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/spadini/mineral-classification
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Sruti-sahini** [comment]
Full name : Sahini Venkata Sitaram Sruti
GitHub Profile Link : https://github.com/Sruti-sahini
Participant ID (If not, then put NA) : 
Approach for this Project : I will try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. I will also do a exploratory data analysis before creating any model.
What is your participant role? JWoC 2024

**Comment by Sruti-sahini** [comment]
Hi @abhisheks008 

Full name : Sahini Venkata Sitaram Sruti
GitHub Profile Link : https://github.com/Sruti-sahini
Participant ID (If not, then put NA) : 
Approach for this Project : I will try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. I will also do a exploratory data analysis before creating any model.
What is your participant role? JWoC 2024

**Comment by abhisheks008** [comment]
Issue assigned to you @Sruti-sahini

**Comment by tanuj437** [comment]
Full name : Tanuj Saxena
GitHub Profile Link : https://github.com/tanuj437
Participant ID (If not, then put NA) : NA
Approach for this Project : Starting with the basic EDA and preprocessing approaches and will test with image classifier models if doesn't provide much accuracy and sensitvity will go for advance models and advance EDA
What is your participant role? SSOC'24

**Comment by abhisheks008** [comment]
Implement 6-7 models for this dataset/problem statement.
Assigned this issue to you @tanuj437
