### ISSUE TITLE
ACI IoT Network Traffic Dataset Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#502]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : ACI IoT Network Traffic Dataset Analysis
:red_circle: **Aim** : The aim of this project is to analyze the traffic dataset given here.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/emilynack/aci-iot-network-traffic-dataset-2023
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by karandomguy** [comment]
**Full name :** Karan Kumar Bhagat
**GitHub Profile Link :** https://github.com/karandomguy
**Participant ID (If not, then put NA) :** NA
**Approach for the Project:**

1. **Exploratory Data Analysis (EDA):**
   - Load the dataset and examine its structure.
   - Handle missing values and clean the data.
   - Conduct univariate, bivariate, and multivariate analysis.
   - Visualize data trends using various plots (histograms, bar charts, scatter plots, etc.).

2. **Feature Engineering:**
   - Create new features if necessary.
   - Encode categorical variables using techniques like one-hot encoding or label encoding.
   - Scale numerical features using standardization or normalization.

3. **Model Building:**
   - Split the dataset into training and testing sets.
   - Implement multiple algorithms (Decision Trees, Random Forest, Gradient Boosting, Logistic Regression, SVM, k-NN).
   - Train and evaluate models using metrics such as accuracy, precision, recall, F1-score, and ROC-AUC.

4. **Model Comparison:**
   - Compare models based on evaluation metrics.
   - Identify the best-performing model.

5. **Documentation and Visualization:**
   - Document data cleaning, EDA, feature engineering, model building, and evaluation.
   - Save visualizations in the "Images" folder.
   - Summarize insights and conclusions.

**What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.):** SSoC

**Comment by abhisheks008** [comment]
One issue at a time @karandomguy

**Comment by karandomguy** [comment]
Yes sure @abhisheks008, will get done with #572 then get started on this

**Comment by why-aditi** [comment]
Full name : Aditi Kala
GitHub Profile Link : https://github.com/why-aditi
Participant ID (If not, then put NA) : NA
Approach for this Project :
Load the data using appropriate tools and conduct an initial inspection to identify missing values and outliers. Perform exploratory data analysis (EDA) to understand feature distributions and relationships. Clean the data by handling missing values and outliers, and engineer new features if necessary. Split the data into training and testing sets, scaling features as needed. Build and evaluate various models. Finalize the best model, evaluate it on the test set, and prepare it for deployment. Document each step and report the findings to ensure clarity and reproducibility.
What is your participant role? SSOC'24

**Comment by abhisheks008** [comment]
Assigned @why-aditi
