### ISSUE TITLE
Crop Production Data Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#504]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Crop Production Data Analysis
:red_circle: **Aim** : The aim of this project is to analyze the dataset using machine learning methods.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/zsinghrahulk/crop-production-data
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by pawaspy** [comment]
@abhisheks008 can you assign me this task?
Full name : Pawas Pandey
GitHub Profile Link : github.com/pawaspy
Participant ID (If not, then put NA) : NA
Approach for this Project : I will use different models such as random forest, gradient boosting or some sequential model to predict the data and matplotlib and seaborn for analysis.
What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.) : IWoC

**Comment by abhisheks008** [comment]
Issue assigned to you @pawaspy

**Comment by abhisheks008** [comment]
@ghousiya47 this issue has been already assigned.

**Comment by abhisheks008** [comment]
> thank you sir for assigning me this oppurtunity, i have done internships on AI ML and created machine learning models, i usually use google collab notebook, but i dont know how to contribute to github, the first step i have to do here is click new issue or pull requests? I joined jwoc peogram late so i didnt attend the class on github contribution, so i apologise for disturbing you.

Issue is already created by me and assigned to you for working. Firstly, you fork this repo in your local system, make the project, upload the files according to the project structure mentioned in the Discord server (I have also pinned the message). Then push your code by making a pull request. You can check out verious YouTube videos for the same to have an idea about it.

**Comment by abhisheks008** [comment]
> thank you sir for assigning me this oppurtunity, i have done internships on AI ML and created machine learning models, i usually use google collab notebook, but i dont know how to contribute to github, the first step i have to do here is click new issue or pull requests? I joined jwoc peogram late so i didnt attend the class on github contribution, so i apologise for disturbing you.

This issue is not assigned to you. Issue #519 is assigned to you, not this one.
@ghousiya47
