### ISSUE TITLE
Most Sold Books in the World Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#508]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Most Sold Books in the World Analysis
:red_circle: **Aim** : The aim of this project is to analyze the most sold books in the world using the given dataset.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/rafsunahmad/most-sold-books-in-the-world
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by mariam7084** [comment]
Hi!! @abhisheks008 
Please assign this issue to me.

Full Name : Mariam
Github Profile Link : https://github.com/mariam7084
Participant ID : NA
Approach for this project : I will perform the EDA of the dataset and visualize the results accordingly.
What is your participant role? JWoC 2024

**Comment by abhisheks008** [comment]
After performing the EDA implement the following models for this project,
1. Random forest
2. Decision tree
3. Logistic regression
4. Lasso
5. Ridge
6. Gradient boosting
7. XgBoost
8. MLP

Check the accuracy scores of the deployed models and find out the best one based on the best accuracy score.

Issue assigned to you @mariam7084

**Comment by mariam7084** [comment]
@abhisheks008 
the dataset contains the following columns:
Books title
Author name
Language
Publish date
Sales
Genre
This dataset can't be used to deploy machine learning models.

**Comment by abhisheks008** [comment]
Then go for extensive visualization and data analysis, make the conclusions according to that. Just like an analysis project.
