### ISSUE TITLE
Viral Shorts Videos Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#509]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Viral Shorts Videos Analysis
:red_circle: **Aim** : The aim of this project is to analyze the viral videos based on the given dataset.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/kanchana1990/viral-shorts-youtubes-most-viewed
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Vidip-Ghosh** [comment]
Can I work on this issue under JWOC 2.0?

**Comment by abhisheks008** [comment]
Implement the following models for this project,
1. Random forest
2. Decision tree
3. Logistic regression
4. Lasso
5. Ridge
6. Gradient boosting
7. XgBoost
8. MLP

Check the accuracy scores of the deployed models and find out the best one based on the best accuracy score.

Are you able to do this? @Vidip-Ghosh

**Comment by Vidip-Ghosh** [comment]
> Implement the following models for this project,
> 
> 1. Random forest
> 2. Decision tree
> 3. Logistic regression
> 4. Lasso
> 5. Ridge
> 6. Gradient boosting
> 7. XgBoost
> 8. MLP
> 
> Check the accuracy scores of the deployed models and find out the best one based on the best accuracy score.
> 
> Are you able to do this? @Vidip-Ghosh

So do I need to all the mentioned model?

**Comment by Vidip-Ghosh** [comment]
> You can take your time, learn along with solving the issue.

Okay then. You can assign.

**Comment by abhisheks008** [comment]
Issue assigned to you @Vidip-Ghosh

**Comment by Vidip-Ghosh** [comment]
Sorry for the delay as I have to study about other algorithms, will raise a PR as soon as it gets completed.

**Comment by abhisheks008** [comment]
Cool. Thanks for the update.

**Comment by abhisheks008** [comment]
Please do not remove the assignment without letting us know @Vidip-Ghosh. It creates confusion as the label marked as `Assigned` but no one is assigned in this issue.

**Comment by HarshRaj29004** [comment]
Full name: Harsh Raj
GitHub Profile Link: https://github.com/HarshRaj29004
Participant ID (If not, then put NA): NA
Approach for this Project:  I will preprocess Data to handle missing values and include required features. Then after finds relation between columns by visually encoding them basically a correlation analysis. Finally, will try to predict views based on likes and comments count.
What is your participant role?  SSOC

**Comment by abhisheks008** [comment]
Implement 5-6 models for this dataset.

Assigned @HarshRaj29004

**Comment by HarshRaj29004** [comment]
Ok i will do it
