### ISSUE TITLE
Sleep Health and Lifestyle Dataset Analysis

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#512]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Sleep Health and Lifestyle Dataset Analysis
:red_circle: **Aim** : The aim of this project is to analyze the given dataset properly using machine learning methods.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/uom190346a/sleep-health-and-lifestyle-dataset
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Yuvika-14** [comment]
hi abhisekh
Full name: Yuvika Singh
git hub profile link:https://github.com/Yuvika-14/Yuvikademo.git
approch: ensemble methods, gradient boosting, neural networks.
Take care of the missing data if there are any categorical values then will use one hot encoder or label encoder depending upon the issue.

**Comment by abhisheks008** [comment]
One issue at a time @Yuvika-14

**Comment by Raj100** [comment]
Raj Rawariya
https://github.com/Raj100
All Regression models
JWoC

**Comment by abhisheks008** [comment]
Hi @Raj100 follow the issue template and put your comments accordingly. Your approach should be to the point and brief, which ensures your determination for this project, if you comment out like this, no one will assign you an issue in a PAN India open source event of highest quality.

Follow this,
- Full name :
- GitHub Profile Link :
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

In your approach mention the specific models you want to work on, how that will help the project, how the models will justify your project with the given dataset, how to measure the best fitted model for this project, all these things should be mentioned. I hope you understand.

@Raj100

**Comment by Raj100** [comment]
Full name :Raj Rawariya
GitHub Profile Link :https://github.com/Raj100
Participant ID (If not, then put NA) :NA
Approach for this Project : Regression and classification models  to try to find health score based on sleep patterns and lifestyle or (make a classification supervised model to identify the lifestyle)
What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.) JWoC

**Comment by abhisheks008** [comment]
Issue assigned to you @Raj100

**Comment by Nishtha1203** [comment]
Nishtha Pabreja
Nishtha1203
Linear Regresion, KNN, Decision Tree, Random Forest
JWoC

**Comment by abhisheks008** [comment]
This issue is already assigned to someone.

**Comment by Sgvkamalakar** [comment]
Hi @abhisheks008 👋🏻, I want to contribute to this issue, please assign it to me  under SSOC.. 🥹

Full name : S G V Kamalakar

GitHub Profile Link : [Sgvkamalakar](https://github.com/Sgvkamalakar)

Participant ID (If not, then put NA): NA

Approach for this Project:  Performing EDA on the dataset, creating visualization plots, and classifying the data based on the Sleep Disorder category using various ML classifiers (like RF, DT, Logistic, etc..) and Feedforward NN models. Developing an interactive UI for predicting outcomes based on user input.

What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.):  SSOC

**Comment by Tanishka023** [comment]
Hey @abhisheks008 Sir, please assign this issue to me, I really want to work on this.

**Comment by Tanishka023** [comment]
Full name : Tanishka Bhalla
GitHub Profile Link: https://github.com/Tanishka023
Participant ID (If not, then put NA) :NA
Approach for this Project : EDA, KNN, Linear Regression
What is your participant role? SSoC'24

**Comment by abhisheks008** [comment]
> Hi @abhisheks008 👋🏻, I want to contribute to this issue, please assign it to me under SSOC.. 🥹
> 
> Full name : S G V Kamalakar
> 
> GitHub Profile Link : [Sgvkamalakar](https://github.com/Sgvkamalakar)
> 
> Participant ID (If not, then put NA): NA
> 
> Approach for this Project: Performing EDA on the dataset, creating visualization plots, and classifying the data based on the Sleep Disorder category using various ML classifiers (like RF, DT, Logistic, etc..) and Feedforward NN models. Developing an interactive UI for predicting outcomes based on user input.
> 
> What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.): SSOC

Implement 5-6 models for this project.

Assigned @Sgvkamalakar

**Comment by Sgvkamalakar** [comment]
> > Hi @abhisheks008 👋🏻, I want to contribute to this issue, please assign it to me under SSOC.. 🥹
> > Full name : S G V Kamalakar
> > GitHub Profile Link : [Sgvkamalakar](https://github.com/Sgvkamalakar)
> > Participant ID (If not, then put NA): NA
> > Approach for this Project: Performing EDA on the dataset, creating visualization plots, and classifying the data based on the Sleep Disorder category using various ML classifiers (like RF, DT, Logistic, etc..) and Feedforward NN models. Developing an interactive UI for predicting outcomes based on user input.
> > What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.): SSOC
> 
> Implement 5-6 models for this project.
> 
> Assigned @Sgvkamalakar

Noted.. 
Thanks for assigning ...
