### ISSUE TITLE
[Project Addition]: Facial Landmark Detection using Python's Mediapipe library

### ISSUE THREAD

**Issue by vishapraj** [abhisheks008/ML-Crate#550]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** :
:red_circle: **Aim** :
:red_circle: **Dataset** :
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by vishapraj** [comment]
@abhisheks008 pls assign me this issue under "JWOC"

**Comment by abhisheks008** [comment]
Need to share the dataset and approach for your project.
@vishapraj

**Comment by vishapraj** [comment]
there will be image to upload section in which after uploading image it will give output facial landmark image.

**Comment by abhisheks008** [comment]
This will not work here, as this project repository solely contains projects based on orthodox machine learning methods, where you have a dataset(s), you do some EDA with the dataset, prepare the models based on it and conclude accordingly.

It's nice approach from you, but I don't think this will be placed here in this repo.
@vishapraj

**Comment by Anshg07** [comment]
Here is the request to assign the issue for the facial landmark detection using Python's Mediapipe library:

Full name: Ansh Gupta
GitHub Profile Link: [Anshg07](https://github.com/Anshg07)
Participant ID: NA
Approach for this Project: I will implement facial landmark detection using Python's Mediapipe library. I will follow the guidelines to create a separate folder named "Facial Landmark Detection". This folder will include subfolders for Images, Dataset, Model, and a requirements.txt file. I will use 3-4 algorithms to implement the models and compare them to determine the best-fitting algorithm based on accuracy scores. Before creating any model, I will perform exploratory data analysis. The Model folder will include a README.md file with proper visualizations and conclusions.
What is your participant role :  Social Summer of Code season 3 (SOCIAL SUMMER OF CODE)

**Comment by Anshg07** [comment]
Full name: Ansh Gupta
GitHub Profile Link: [Anshg07](https://github.com/Anshg07)
Participant ID: NA
Approach for this Project: I will implement facial landmark detection using Python's Mediapipe library. The project involves setting up the environment, installing necessary packages, and creating a project structure with folders for Images, Dataset, Model, and requirements.txt. I will write a script to perform facial landmark detection and visualize the results. I will also compare the performance of Mediapipe with other algorithms such as Dlib and OpenCV, performing exploratory data analysis and documenting findings in the Model folder's README.md. The project will include unit and integration testing, and the system will be deployed for real-time use if necessary.
What is your participant role? : Social Summer of Code season 3 (SSOC 3)

**Comment by abhisheks008** [comment]
Assigned @Anshg07
