### ISSUE TITLE
World Population Growth Analysis

### ISSUE THREAD

**Issue by mariam7084** [abhisheks008/ML-Crate#560]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : World Population Growth Analysis
:red_circle: **Aim** : to analyze the dataset
:red_circle: **Dataset** :https://www.kaggle.com/datasets/rafsunahmad/world-population-growth
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Mariam
- GitHub Profile Link : github.com/mariam7084
- Participant ID (If not, then put NA) : NA
- Approach for this Project : perform EDA and visualization
- What is your participant role? JWoC 2024

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

@abhisheks008 Please assign this issue to me.

**Comment by pawaspy** [comment]
@abhisheks008 can you assign me this issue.
Full name : Pawas Pandey
GitHub Profile Link : github.com/pawaspy
Participant ID (If not, then put NA) : NA
Approach for this Project : perform EDA and visualization
What is your participant role? IWoC 2024

**Comment by abhisheks008** [comment]
Go ahead @mariam7084. Assigned to you under JWOC

**Comment by prakharsingh-74** [comment]
@abhisheks008 can you assign me this issue.
Full name : Prakhar Singh
GitHub Profile Link : github.com/prakharsingh-74
Participant ID (If not, then put NA) : NA
Approach for this Project : perform EDA and apply some useful algorithms according to the dataset
What is your participant role? JWoC 2024

**Comment by abhisheks008** [comment]
Already assigned.

**Comment by prakharsingh-74** [comment]
you have assigned this issue last week if not have any update please assigned it to me

**Comment by abhisheks008** [comment]
Hi @mariam7084 what's the update on this issue?

**Comment by mariam7084** [comment]
Hi @abhisheks008 ! 
I am halfway through the project. Had been busy due to starting of new semester. Will make a PR by by tomorrow at most.
