### ISSUE TITLE
Body Posture Detection and Prediction 

### ISSUE THREAD

**Issue by Nishtha1203** [abhisheks008/ML-Crate#565]
Body Posture Detection and Prediction 
Nishtha Pabreja
Nishtha1203 (github)
Linear Regression, KNN, Decision Tree

**Comment by abhisheks008** [comment]
Share the dataset and approach for this project.

**Comment by abhisheks008** [comment]
https://github.com/abhisheks008/ML-Crate/issues/111

The issue is already created, why have you created a new issue. No need to create a new issue, you can comment out in the existing issue with your approach to get assigned.
