### ISSUE TITLE
[Feature Addition]: Web App for Vehicle Live Risk Prediction

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#602]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : [Feature Addition]: Web App for Vehicle Live Risk Prediction
</br></br>:red_circle: **Aim** : The aim is to create a web app for the [Vehicle Live Risk Prediction](https://github.com/abhisheks008/ML-Crate/tree/main/Vehicle%20Live%20Risk%20Prediction) project. Use the best existing model in the project folder. Follow the [Web App README template](https://github.com/abhisheks008/ML-Crate/blob/main/.github/web-app-readme-template.md) for the same.
</br></br>:red_circle: **Dataset** : N/A
</br></br>:red_circle: **Approach** : Try to create a Flask/Streamlit app for the existing project.
</br></br>🔴 **Reference Project Folder**: [Brain Tumor Detection](https://github.com/abhisheks008/DL-Simplified/tree/main/Brain%20Tumor%20Detection)

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by shivansh-2003** [comment]
Can You Please Assign this issue under SSOC. 2024 Season 3
Shivansh Mahajan
Github:- https://github.com/shivansh-2003
Participation ID:- NA
I will make a pickle file of the Fitted ML model and then deploy it to Streamlit Python Framework to display the feature and predict the quality . I am well versed with making Streamlit App you can check out my linkedin :-https://www.linkedin.com/in/shivansh-mahajan-13227824a/ and Git repository .
My some recent Project in Streamlit https://www.linkedin.com/feed/update/urn:li:activity:7199784822737682432/(SPAM classifier)
https://www.linkedin.com/feed/update/urn:li:activity:7201206409605091328/ . (NLP APP)
Participation Role:- SSOC Season 3

**Comment by abhisheks008** [comment]
Contributions will start from June 1, 2024. Till then please have some patience.

**Comment by shivansh-2003** [comment]
Can You Please Assign this issue under SSOC. 2024 Season 3
Shivansh Mahajan
Github:- https://github.com/shivansh-2003
Participation ID:- NA
I will make a pickle file of the Fitted ML model and then deploy it to Streamlit Python Framework to display the feature and predict the Risk Assessment Of Vehicle . I am well versed with making Streamlit App you can check out my linkedin :-https://www.linkedin.com/in/shivansh-mahajan-13227824a/ and Git repository .
My some recent Project in Streamlit https://www.linkedin.com/feed/update/urn:li:activity:7199784822737682432/(SPAM classifier)
https://www.linkedin.com/feed/update/urn:li:activity:7201206409605091328/ . (NLP APP)
can u assign me with this issue @abhisheks008
Participation Role:- SSOC Season 3

**Comment by abhisheks008** [comment]
Cool go ahead. @shivansh-2003

**Comment by shivansh-2003** [comment]
Thanks sir , @abhisheks008 for assigning issue to me

**Comment by shivansh-2003** [comment]
![Screenshot 2024-06-03 at 10 05 16 PM (2)](https://github.com/abhisheks008/ML-Crate/assets/144326194/5ed3e5cb-5a68-4052-b5cc-a04ccbc01da6)
![Screenshot 2024-06-03 at 10 05 04 PM (2)](https://github.com/abhisheks008/ML-Crate/assets/144326194/e03a9d0d-37d9-4624-8547-74f2a5a49fc7)
![Screenshot 2024-06-03 at 10 04 50 PM (2)](https://github.com/abhisheks008/ML-Crate/assets/144326194/706d8b9c-0c81-4458-afa1-b518b8735f4e)
![Screenshot 2024-06-03 at 10 03 46 PM (2)](https://github.com/abhisheks008/ML-Crate/assets/144326194/3dc1c44f-125e-4e40-a83b-27b3dfef2764)

My app work of streamlit is it enough or need changes

**Comment by abhisheks008** [comment]
Have you used the existing model which is best fitted as in the existing project?

**Comment by shivansh-2003** [comment]
Yes Xgboost

**Comment by abhisheks008** [comment]
Create your pull request for review.
