### ISSUE TITLE
[Project Addition]: Bank Customer Churn Prediction with Web App

### ISSUE THREAD

**Issue by NIKITA320495** [abhisheks008/ML-Crate#609]
creating end to end bank customer churn prediction using machine learning libraries and integrating it with  front end with flask

**Comment by abhisheks008** [comment]
Share your details along with the dataset source, approach for solving this issue.
@NIKITA320495

**Comment by NIKITA320495** [comment]
This project involves developing an end-to-end bank customer churn prediction system using machine learning and integrating it with a Flask-based frontend. We collect and preprocess customer data, perform exploratory data analysis, and engineer features. Various models are trained and evaluated, with the best-performing model being serialized. We can use algorithms like logistic regression,SVM, XGboost , Random forest,etc.The Flask API handles user input, preprocessing, and prediction. The frontend, designed with HTML ,CSS and JS, allows users to input data and view predictions. The entire system undergoes unit and integration testing before deployment to a web server. Continuous monitoring and periodic model updates ensure accuracy and reliability.

dataset used:Churn_Modelling.csv from kaggle
The bank customer churn dataset is a commonly used dataset for predicting customer churn in the banking industry. It contains information on bank customers who either left the bank or continue to be a customer. The dataset includes the following attributes:

Customer ID: A unique identifier for each customer
Surname: The customer's surname or last name
Credit Score: A numerical value representing the customer's credit score
Geography: The country where the customer resides (France, Spain or Germany)
Gender: The customer's gender (Male or Female)
Age: The customer's age.
Tenure: The number of years the customer has been with the bank
Balance: The customer's account balance
NumOfProducts: The number of bank products the customer uses (e.g., savings account, credit card)
HasCrCard: Whether the customer has a credit card (1 = yes, 0 = no)
IsActiveMember: Whether the customer is an active member (1 = yes, 0 = no)
EstimatedSalary: The estimated salary of the customer
Exited: Whether the customer has churned (1 = yes, 0 = no)

**Comment by Anshg07** [comment]
Full name: Ansh Gupta
GitHub Profile Link: [Anshg07](https://github.com/Anshg07)
Participant ID: NA
Approach for this Project: I will develop an end-to-end bank customer churn prediction system using machine learning and integrate it with a Flask-based frontend. The project will involve collecting and preprocessing the Churn_Modelling.csv dataset from Kaggle, performing exploratory data analysis, and engineering features. I will train and evaluate various models, including logistic regression, SVM, XGBoost, and Random Forest, and serialize the best-performing model. The Flask API will handle user input, preprocessing, and prediction, while the frontend, designed with HTML, CSS, and JS, will allow users to input data and view predictions. The system will undergo unit and integration testing before deployment to a web server. Continuous monitoring and periodic model updates will ensure accuracy and reliability.

**Comment by abhisheks008** [comment]
Implement 5-6 models for this project and then use the best fitted model for the web app.

Assigned @NIKITA320495
