### ISSUE TITLE
[Project Addition]: End to End Email spam classifier 

### ISSUE THREAD

**Issue by codewithpiyushh** [abhisheks008/ML-Crate#614]
### ML-Crate Repository (Proposing new issue)
:red_circle: **End to End Email spam classifier** :
:red_circle: **to make an End to End Email spam classifier using natural language process which will improve the  effictiveness ** :
:red_circle: **https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset** :
:red_circle: **Approach** : Try to use 3-4 algorithms and natural language process to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model. with that creating seperate web for that

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : piyush
- GitHub Profile Link : https://github.com/codewithpiyushh
- Participant ID (If not, then put NA) : contributor
- Approach for this Project : 
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.) SSOC

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
What are the machine learning models you are planning to implement?
@codewithpiyushh

**Comment by codewithpiyushh** [comment]
i am thinking of doing it with naive bayes, SVM and my main motive is to do it with NLP

**Comment by abhisheks008** [comment]
Implement at least 5-6 models for this project.

Assigned @codewithpiyushh
