### ISSUE TITLE
[Project Addition]: Tourist Destination Recommendation System

### ISSUE THREAD

**Issue by UTSAVS26** [abhisheks008/ML-Crate#620]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Tourist Destination Recommendation System
:red_circle: **Aim** :  Implement a recommendation system to suggest tourist destinations based on user preferences, travel history, and social media interactions.
:red_circle: **Dataset** : Aggregate data from travel websites, social media platforms, and user reviews to create a comprehensive tourist destination dataset.
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also, do not forget to do exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Utsav SInghal
- GitHub Profile Link : https://www.github.com/UTSAVS26/
- Participant ID (If not, then put NA) : Contributor
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.): SSOC

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Anshg07** [comment]
Full name: Ansh Gupta  
GitHub Profile Link: [Anshg07](https://github.com/Anshg07)  
Participant ID: NA  
Approach for this Project: I will implement a recommendation system to suggest tourist destinations based on user preferences, travel history, and social media interactions. I will aggregate data from travel websites, social media platforms, and user reviews to create a comprehensive tourist destination dataset. I will use 3-4 algorithms to implement the models and compare them to find the best-fitting algorithm based on accuracy scores. Before creating any model, I will perform exploratory data analysis. Following the guidelines, I will create a separate folder named "Tourist Destination Recommendation System" with subfolders for Images, Dataset, Model, and a requirements.txt file. The Model folder will include a README.md file with proper visualizations and conclusions.  
What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.): **Social Summer of Code season 3 (SOCIAL SUMMER OF CODE)**

**Comment by abhisheks008** [comment]
Implement the following models for this project,
1. Random Forest
2. Decision Tree
3. Logistic Regression
4. Gradient Boosting
5. XGBoost
6. Lasso
7. Ridge
8. MLP Classifier
9. Support Vector Machine

Assigned @UTSAVS26
