### ISSUE TITLE
[PROJECT ADDITION]- PCOS DETECTION 

### ISSUE THREAD

**Issue by payalsinha12** [abhisheks008/ML-Crate#624]
Polycystic Ovary Syndrome (PCOS) is a hormonal imbalance affecting women of childbearing age. Early detection is crucial for proper management. Machine learning offers a promising approach to aid in PCOS diagnosis. 
The project's core is a well-structured dataset containing patient information relevant to PCOS diagnosis. This data might include:
Demographic details (age, weight, etc.)
Medical history (menstrual irregularities, acne, etc.)
Lab test results (hormone levels, ultrasound findings)
I will take the dataset from Kaggle and prepare a model for it . I will create a separate folder named as the Project Title.
Inside that folder, there will be four main components.
Images - To store the required images.
Dataset - To store the dataset or, information/source about the dataset.
Model - To store the machine learning model you've created using the dataset.
requirements.txt - This file will contain the required packages/libraries to run the project in other machines.
Inside the Model folder, the README.md file must be filled up properly, with proper visualizations and conclusions.
 
@abhisheks008 please assign me this project .

**Comment by payalsinha12** [comment]
@abhisheks008 please assign me the project

**Comment by abhisheks008** [comment]
Which models are you planning to implement?
@payalsinha12

**Comment by abhisheks008** [comment]
> i will implement a model using different classifiers which will helps a person to determine that she was suffering from pcos or not after preparation of model if someone wants to use frontend and backend for it they can @abhisheks008

Use these models for your project,
1. Random Forest
2. Decision Tree
3. Logistic Regression
4. XGBoost
5. Lasso
6. Ridge
7. Gradient Boosting
8. KNN
9. Naive Bayes
10. MLP Classifier

Assigned @payalsinha12
