### ISSUE TITLE
Real time trader using the dataset for a specified period 

### ISSUE THREAD

**Issue by AI-ApeX-DeV** [abhisheks008/ML-Crate#630]
My project aims to create a real time trader which will do trading and will show real time results after each trade done 
It will be for BTC/USDT
it will sell,buy and hold based on the logic and each transaction will be displayed at everystep based on the frequency of trading. 3m,5m,15m,30m,2hr,4hr,6hr.  

here is a screenshot of what output will look like 

![image](https://github.com/abhisheks008/ML-Crate/assets/99337487/b6828917-d4e1-4748-898e-c3878eb198b0)
![image](https://github.com/abhisheks008/ML-Crate/assets/99337487/05b39cba-e41b-4aaf-9ea8-5357f0a4234f)

**Comment by abhisheks008** [comment]
Closing this issue as not required for this project repository.
