### ISSUE TITLE
Medical Recommendation System

### ISSUE THREAD

**Issue by Shiroirose** [abhisheks008/ML-Crate#631]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Medical Recommendation System
:red_circle: **Aim** :  A personalized medical recommendation system to assist users in understanding and managing their health by writing symptoms and getting the probable health issue as output through multiclass classification 
:red_circle: **Dataset** : to be taken from Kaggle
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************

white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sebonti Patra
- GitHub Profile Link : https://github.com/Shiroirose
- Participant ID (If not, then put NA) : NA
- Approach for this Project : I will use 5-6 algorithms like SVM, Random Forest, GradientBoosting, KNN, logistic, naive bayes for multiclass classification and compare the accuracy of the best model using roc score and accuracy
- What is your participant role? : SSOC 03'24

**Comment by gayatri-p786** [comment]
Full name : Gayatri Patil
GitHub Profile Link : https://github.com/gayatri-p786
Participant ID (If not, then put NA) : NA
Approach for this Project : I will use 5-6 algorithms like Logistic Regression, SVM, Random Forest, GradientBoosting, CNN, logistic, naive bayes for multiclass classification and compare the accuracy of the best model using accuracy
What is your participant role? : SSOC 03'24

**Comment by abhisheks008** [comment]
Hi @Shiroirose can you please share your approach and a brief about the models you are planning to implement here for this dataset? Mention at least 6-7 models for this dataset.

**Comment by Shiroirose** [comment]
@abhisheks008 I will do EDA on the dataset and  use  algorithms like SVM, Random Forest, GradientBoosting, KNN, logistic Regression, naive bayes, Decision trees and finally ANN for multiclass classification and compare the accuracy of the best model using roc score and accuracy.

**Comment by abhisheks008** [comment]
Assigned @Shiroirose
