### ISSUE TITLE
[Project Addition] Predicting Molecular Properties

### ISSUE THREAD

**Issue by Sgvkamalakar** [abhisheks008/ML-Crate#636]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title**: Predicting Molecular Properties
:red_circle: **Aim**: To perform Exploratory Data Analysis (EDA) on the datasets and predict the `scalar_coupling_constant` between atom pairs in molecules using ML/DL models.
:red_circle: **Dataset**:  https://www.kaggle.com/competitions/champs-scalar-coupling/data
:red_circle: **Approach**: Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do an exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  S G V Kamalakar

- GitHub Profile Link : [Sgvkamalakar](https://github.com/Sgvkamalakar)

- Participant ID (If not, then put NA) : NA

- Approach for this Project:
```bash
   - Data preprocessing and transformation.
   - EDA and visualization.
   - Feature Engineering.
   - Training ML models like RF, DT, SVM, KNN, Linear regressor, and other ML regressors for predicting the `scalar_coupling_constant` and evaluating the best-fitted model for the dataset.
   - Utilizing the power of Neural Networks and Graph Neural Networks which can be best fitted for molecular data.
   - Making predictions using best-fitted models.  
```

- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.): SSOC S3

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Sgvkamalakar** [comment]
@abhisheks008, assign this issue to me!! 🙂

**Comment by abhisheks008** [comment]
Assigned @Sgvkamalakar
