### ISSUE TITLE
Creating a User driven Web App for Body Fat Prediction

### ISSUE THREAD

**Issue by imksprateek** [abhisheks008/ML-Crate#645]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Creating a User driven web application for an existing model
</br></br>:red_circle: **Aim** : The aim is to create a web app for the [Body Fat Prediction](https://github.com/abhisheks008/ML-Crate/tree/main/Body%20Fat%20Prediction) project. 
</br></br>:red_circle: **Dataset** : N/A
</br></br>:red_circle: **Approach** : I will create a User driven Web application for the existing project [Body Fat Prediction](https://github.com/abhisheks008/ML-Crate/tree/main/Body%20Fat%20Prediction) based on Flask Framework and Pickle to dump the model. 
</br></br>🔴 **Reference Project Folder**: [Body Fat Prediction](https://github.com/abhisheks008/ML-Crate/tree/main/Body%20Fat%20Prediction)
**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  K S Prateek
- GitHub Profile Link : https://github.com/imksprateek
- Participant ID (If not, then put NA) : NA
- Approach for this Project : I'm going to use Pickle in the existing project to dump the model and then integrate the model with Flask based Web application, according to the provided guidelines and create Documentation for the same
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.): SSoC - Social Summer of Code - contributor

I'm requesting to assign this issue to me

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by imksprateek** [comment]
Requesting to assign this issue to me : @imksprateek

**Comment by abhisheks008** [comment]
Assigned @imksprateek

**Comment by imksprateek** [comment]
@abhisheks008 I have created a PR: #660 adding this feature
