### ISSUE TITLE
AI CHATBOT

### ISSUE THREAD

**Issue by Garvanand** [abhisheks008/ML-Crate#658]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Customer support chatbot** :
:red_circle: **To provide customer support assistance** :
:red_circle: **Intents.json is being used as a dataset** :
:red_circle: **Approach** : PyTorch and Natural Language Toolkit is used to formulate this customer support chatbot

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Garv Anand
- GitHub Profile Link : www.github.com/Garvanand
- Participant ID (If not, then put NA) :NA
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)
- GSSoC,SSoC

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Without getting assigned to an issue you can not create a pull request. Also this repository mainly focuses on complete machine learning projects, implementing a chatbot will not work here.

Anyways thanks for your approach. Closing this issue as not required.
