### ISSUE TITLE
Netflix Movies and TV Shows

### ISSUE THREAD

**Issue by ASLManasa** [abhisheks008/ML-Crate#66]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Netflix Movies and TV Shows
:red_circle: **Aim** : To understand what content is available in different countries ,Identify similar content by matching text-based features ,Network analysis of Actors / Directors and find interesting insights ,Does Netflix has more focus on TV Shows than movies in recent years?. Perform EDA.
:red_circle: **Dataset** : https://www.kaggle.com/shivamb/netflix-shows
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/abhisheks008/ML-Crate/tree/main/Project-Demo-Folder

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- Are you a participant of SWOC 2.0?
    - [ ] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Swastyy** [comment]
Hi @ASLManasa , I want to take this issue.
- SWASTIKA GUPTA
- [Swastyy](https://github.com/Swastyy)
- not sure where it is mentioned.
- Country wise analysis for trending shows/binge, more searches of tv shows or movies in netflix by analysing the test data
- Yes, I am a participant.

Can you tell me how the score for fixing this issue will be calculated? Thanks.

**Comment by ASLManasa** [comment]
@Swastyy ok Assigning to you.  Try completing within 3 days. You can check the kaggle code section. You will get an idea.

**Comment by abhisheks008** [comment]
![image](https://user-images.githubusercontent.com/68724349/148686996-11771f32-aee9-4f73-87af-567d70cd9b5f.png)

Is this you?

**Comment by Swastyy** [comment]
> Is this you? @Swastyy
Yes, where did you get it?

**Comment by abhisheks008** [comment]
If you have joined the ml-crate channel created by SWOC team then I think you must have knew it.

**Comment by abhisheks008** [comment]
@Swastyy what's the update here for this project?

**Comment by sankalp-srivastava** [comment]
Full name : Sankalp Srivastava
GitHub Profile Link : www.github.com/sankalp-srivastava
Participant ID : 857
Approach for this Project : A detailed EDA and creating different models and comparing them.
Are you a participant of SWOC 2.0?

- [x] YES
- [ ] NO

**Comment by ASLManasa** [comment]
@sankalp-srivastava go ahead!
