### ISSUE TITLE
Sarcasm Detection Model using Machine Learning(NLP)

### ISSUE THREAD

**Issue by KamakshiOjha** [abhisheks008/ML-Crate#661]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Sarcasm Detection Model Comparison
:red_circle: **Aim** : To determine the best-performing machine learning model for sarcasm detection in headlines by comparing multiple algorithms based on accuracy scores.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/rmisra/news-headlines-dataset-for-sarcasm-detection
:red_circle: **Approach** : Try to use 3-4 algorithms (such as Embedding + GlobalAveragePooling1D, Embedding + Bidirectional LSTM, Embedding + Conv1D + Bidirectional LSTM) to implement the models. Perform exploratory data analysis (EDA) on the dataset before creating any models to understand its characteristics.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Kamakshi Ojha
- GitHub Profile Link : https://github.com/KamakshiOjha
- Approach for this Project : 
Architecture: Embedding layer, two Conv1D layers (128 and 64 filters), followed by a Bidirectional LSTM layer (32 units) and Dense layers.
Purpose: Combines convolutional layers with LSTMs to extract local features and capture temporal dependencies.
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.) VSOC

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Assigned to you @KamakshiOjha 
Try to implement 6-7 models for this problem statement.
