### ISSUE TITLE
Predicting Airbnb Listing Prices in New York City

### ISSUE THREAD

**Issue by awesohame** [abhisheks008/ML-Crate#671]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Predicting Airbnb Listing Prices in New York City
:red_circle: **Aim** : Predict Airbnb listing prices based on various features.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/dgomonov/new-york-city-airbnb-open-data
:red_circle: **Approach** : 
1. **Exploratory Data Analysis (EDA)**:
   - Analyze data distribution, patterns, and anomalies.
   - Visualize relationships between features and price.

2. **Data Preprocessing**:
   - Handle missing values.
   - Drop unnecessary columns.
   - Encode categorical variables.
   - Scale numerical features.

3. **Model Training and Evaluation**:
   - Split data into training and testing sets.
   - Train regression models:
     - Linear, Decision Tree, Random Forest, Gradient Boosting.
   - Evaluate with metrics like MAE, MSE, R2.
   - Compare model performance to select best fit.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Soham Aversekar
- GitHub Profile Link : https://github.com/awesohame
- Participant ID (If not, then put NA) : NA
- Approach for this Project : Perform Exploratory Data Analysis (EDA) to understand data distribution and visualize feature relationships. Preprocess data by handling missing values, dropping unnecessary columns, encoding categorical variables, and scaling numerical features. Train multiple regression models, evaluate using metrics like MAE, MSE, and R2, and select the best-performing model. 
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.) : VSoC

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by awesohame** [comment]
Please assign me @awesohame this issue under VSoC.

**Comment by abhisheks008** [comment]
Can you implement 6-7 models for this project?

**Comment by awesohame** [comment]
@abhisheks008 Yes, I can train 6-7 models

**Comment by abhisheks008** [comment]
Assigned @awesohame

**Comment by adi271001** [comment]
Full name : Aditya D
GitHub Profile Link : https://github.com/adi271001
Participant ID (If not, then put NA) : NA
Approach for this Project : 
1. Data Cleaning 
2. Data preprocessing
3. EDA
4. Feature Engineering
5. Modelling and evaluation
6. Hyperparameter Tuning
7. Feature Importance
What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.) : SSOC Contributor

**Comment by abhisheks008** [comment]
Assigned @adi271001
