### ISSUE TITLE
Term Deposit Prediction

### ISSUE THREAD

**Issue by Sgvkamalakar** [abhisheks008/ML-Crate#680]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title**: Term Deposit Prediction
:red_circle: **Aim**: This project aims to predict whether a client will subscribe to a term deposit based on data from direct marketing campaigns.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/henriqueyamahata/bank-marketing/data
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do an exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID (If not, then put NA) :
- Approach for this Project :
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Sgvkamalakar** [comment]
Hi @abhisheks008 👋🏻, I want to contribute to this issue, please assign it to me under SSOC.. 🥹

**Full name** : S G V Kamalakar

**GitHub Profile Link** : [Sgvkamalakar](https://github.com/Sgvkamalakar)

**Participant ID (If not, then put NA)**: NA

**Approach for this Project:** I will conduct EDA and attribute relationship analysis, apply various machine learning classifiers such as **Logistic Regression, KNN, SVM, Decision Tree, and  Random Forest**, and compare their performance to determine the best fit for the data.

**What is your participant role?**: SSOC

**Comment by why-aditi** [comment]
Full name : Aditi Kala

GitHub Profile Link : https://github.com/why-aditi

Participant ID (If not, then put NA): NA

Approach for this Project: Start by cleaning the dataset to handle missing values and outliers. Next, transform categorical variables using techniques like one-hot encoding and normalize numerical features. Perform exploratory data analysis (EDA) to identify patterns and correlations. Split the data into training and testing sets. Use models such as logistic regression, decision trees, or more advanced methods like random forests and gradient boosting. Evaluate model performance using metrics like accuracy, precision, recall, and the F1 score.

What is your participant role?: SSOC'24

**Comment by kom-senapati** [comment]
Hi @abhisheks008 👋🏻, It's my first time here and I wanna start contributing, please assign it to me under SSOC

Full name : K Om Senapati

GitHub Profile Link : [K Om Senapati](https://github.com/kom-senapati)

Participant ID (If not, then put NA): NA

Approach for this Project: I will do EDA first then data cleaning and data transformation if needed. After that, I will split data sets into training and testing sets. Then will use scaling and test with models like Logistic Regression, SVM, Random Forest, and Gradient Boost and find a good model with high accuracy and F1 score.

What is your participant role?: SSOC

**Comment by abhisheks008** [comment]
Hi @why-aditi and @kom-senapati thanks for showing your interest. As this issue is opened by @Sgvkamalakar, hence assigning this issue to him.

Assigned @Sgvkamalakar
