### ISSUE TITLE
Loan Repayment Prediction

### ISSUE THREAD

**Issue by aviralgarg05** [abhisheks008/ML-Crate#692]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Loan Repayment Prediction
:red_circle: **Aim** : To predict the loan repayment 
:red_circle: **Dataset** :  https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/loan_train.csv
:red_circle: **Approach** :  1. Data Preprocessing 2. Data Visualization 3. Train, Test, Split  4. Modelling- DT, RF 5. Metrics and Evaluation

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Aviral Garg
- GitHub Profile Link : https://github.com/aviralgarg05
- Participant ID (If not, then put NA) : NA
- Approach for this Project : 1. Data Preprocessing 2. Data Visualization 3. Train, Test, Split  4. Modelling- DT, RF 5. Metrics and Evaluation
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.) : SSOC Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Annarhysa** [comment]
Please assign me this issue @aviralgarg05 @abhisheks008

**Comment by abhisheks008** [comment]
Hi @aviralgarg05 implement 6-7 models for this problem statement. Assigned this issue to you.
