### ISSUE TITLE
Boston House Price Prediction

### ISSUE THREAD

**Issue by payalsinha12** [abhisheks008/ML-Crate#695]
### ML-Crate Repository (Proposing new issue)
🔴 **Project Title** : Boston House Price Prediction 
🔴 **Aim** : The Boston House Price Prediction project aims to predict the median value of owner-occupied homes in the Boston area. 
🔴**Dataset** : (https://lib.stat.cmu.edu/datasets/boston)
🔴 **Approach** : 1. Project Setup and Planning
Define the scope and goals of the project.
Gather all necessary libraries and tools.
Understand the dataset and its features.
2. Data Collection and Understanding
Load the Dataset:
Use sklearn.datasets.load_boston to load the Boston housing dataset.
Convert the dataset to a Pandas DataFrame for easier manipulation and analysis.
Initial Exploration:
Display the first few rows of the dataset to understand its structure.
Get a summary of the dataset to see the number of features, target variable, and data types.
3. Exploratory Data Analysis (EDA)
Visualize Data:
Use histograms to visualize the distribution of features and the target variable.
Correlation Analysis:
Create a correlation matrix heatmap to understand the relationships between features and the target variable.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Payal Sinha
- GitHub Profile Link : https://github.com/payalsinha12
- Participant ID (If not, then put NA) :
- Approach for this Project : The Boston House Price Prediction project aims to predict the median value of owner-occupied homes in the Boston area. 
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.) SSoc

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by payalsinha12** [comment]
@das-ankur please assign my this issue .

**Comment by abhisheks008** [comment]
Hi @payalsinha12 this problem statement is already solved. Closing this issue as duplicate.
