### ISSUE TITLE
[Project Addition] Emotion recognition from Speech

### ISSUE THREAD

**Issue by JashwanthSA** [abhisheks008/ML-Crate#697]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Emotion Recognition from Speech
:red_circle: **Aim** : To predict Emotion from audio files
:red_circle: **Dataset** : https://www.kaggle.com/datasets/ejlok1/toronto-emotional-speech-set-tess
:red_circle: **Approach** : I would use the TESS dataset to train the LSTM model and plot the results in a graph.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Jashwanth SA
- GitHub Profile Link : https://github.com/JashwanthSA
- Participant ID (If not, then put NA) : NA
- Approach for this Project :
  - Load audio files from the TESS dataset
  - Feature Extraction
  - Train the LSTM model 
  - Plot the results
- What is your participant role? SSOC '24

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Hi @JashwanthSA it's a nice problem statement, but in this repository we always build 5-6 models for any dataset and then check the most fitted model based on the accuracy scores. You need to upgrade your approach as per the needs of this repo.

**Comment by JashwanthSA** [comment]
Fine @abhisheks008 , haven't thought about it. I will upgrade my approach and let you know when I'm ready.

**Comment by Harshit-code-tech** [comment]
i would like to grap it....
and speaking of models.. i will use cnn, lstm, hybrid... and in performance optimizer...
Adam, RMSprop, Adagrad, Adadelta, Adamax, Nadam, SGD
and instead of tess.. i will use 4 dataset...
tess(dataset already mentioned...)
,ravdess,(https://www.kaggle.com/datasets/uwrfkaggler/ravdess-emotional-speech-audio)
savee,(https://www.kaggle.com/datasets/ejlok1/surrey-audiovisual-expressed-emotion-savee)
crema..(https://www.kaggle.com/datasets/ejlok1/cremad)
and i will make a gui so that it be esaily interective.. speaking of accuracy.. will try to achieve 70%..

**Comment by abhisheks008** [comment]
To be honest pure deep learning projects are not meant to be for this repository. Hence I have decided to close this issue as this will not fit the genre of the repository.
