### ISSUE TITLE
add AI Generated Fruits and Real Fruits Classification using Image Processing

### ISSUE THREAD

**Issue by ananyag309** [abhisheks008/ML-Crate#707]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : AI Generated Fruits and Real Fruits Classification using Image Processing
</br></br>:red_circle: **Aim** : The aim of this project is to identify and differentiate between images of real fruits and AI generated fruits using Image Processing methods.
</br></br>:red_circle: **Dataset** : https://www.kaggle.com/datasets/osmankagankurnaz/dataset-of-ai-generated-fruits-and-real-fruits
</br></br>:red_circle: **Approach** : The project aims to classify a dataset consisting of images of apples (red/green) photographed from different angles into AI generated images or real images, irrespective of the type/color of apple. To achieve this, images need to be preprocessed and then trained on various models (at least 3), after which predictions are made for some input image. Finally, accuracy of models is compared to provide the best output.
</br></br>🔴 **Reference Project Folder**: 
**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Ananya Gupta
- GitHub Profile Link : https://github.com/ananyag309
- What is your participant role? SSOC

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
This will not work here. Closing this issue as not working.
