### ISSUE TITLE
E commerce shipping analysis

### ISSUE THREAD

**Issue by adi271001** [abhisheks008/ML-Crate#714]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : E-commerce shipping analysis
:red_circle: **Aim** : to analyze the e-commerce shippign data using ml models
:red_circle: **Dataset** : https://www.kaggle.com/datasets/prachi13/customer-analytics
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.
1. data cleaning
2. data prepocessing
3. eda
4. modelling
5. evaluation
**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Aditya D
- GitHub Profile Link :  www.github.com/adi271001
- Participant ID (If not, then put NA) : NA
- Approach for this Project :
1. data cleaning
2. data prepocessing
3. eda
4. modelling using models like logistic regression , random forest , knn , adaboost , catboost , xgboost , graidentboost
5. evaluation
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.) SSOC Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by vishalmaurya850** [comment]
Please assign this issue to me.

**Comment by abhisheks008** [comment]
Hi @adi271001 what are models you are planning for this project? Sorry for replying late.

**Comment by adi271001** [comment]
1. logistic regression
2. random forest
3. SVM
4. adaboost
5. xgboost
6. gradientboost
7. catboost
8. decision tree
9. extra trees

@abhisheks008 this is what i'll be using

**Comment by abhisheks008** [comment]
Assigned @adi271001
