### ISSUE TITLE
IPL Winning Match Prediction

### ISSUE THREAD

**Issue by krishna-NIT** [abhisheks008/ML-Crate#72]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : IPL Winning Match Prediction
:red_circle: **Aim** : Predict the winning Team made by a different player with different bowlers, batsmen, and captains. Will be finalizing the best method to be used on behalf of accuracy. Predicting some outcomes of upcoming matches
:red_circle: **Dataset** : https://bit.ly/34SRn3b
:red_circle: **Approach** : Initially cleaning & EDA with ungrouping players from Team to individual players and then applying various techniques to find the best accuracy

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/abhisheks008/ML-Crate/tree/main/Project-Demo-Folder

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shrikrushna Bhagwat
- GitHub Profile Link : https://github.com/krishna-nit
- Participant ID : 930
- Approach for this Project : Initially cleaning & EDA with ungrouping players from Team to individual players and then applying various techniques to find the best accuracy
- Are you a participant of SWOC 2.0?
    - [x] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by krishna-NIT** [comment]
@abhisheks008 I want to work on this so, Please assign it to me 👍🏻

**Comment by abhisheks008** [comment]
One issue at a time @krishna-NIT

**Comment by krishna-NIT** [comment]
> One issue at a time @krishna-NIT

Yes @abhisheks008, You can assign me, Right now I have 0 assigned issues

**Comment by abhisheks008** [comment]
Try to implement 4-5 algorithms for the model creation and check the accuracy of the algorithms to find out the best fitted model for this project @krishna-NIT.

Issue assigned to you.
