### ISSUE TITLE
Parameters of Cricket Analysis

### ISSUE THREAD

**Issue by SOMNATH0904** [abhisheks008/ML-Crate#723]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Exploratory Data Analysis (Sports)
</br></br>:red_circle: **Aim** : It is a comprehensive guide for conducting EDA on sports-related datasets. It aims to equip users with the skills necessary to uncover insights and patterns from raw data, leveraging various statistical and graphical techniques. This project covers a range of essential EDA steps, including data cleaning, data visualization, and summary statistics. Users will learn how to handle missing values, identify outliers, and understand the distribution and relationships within the data. The project provides practical examples and code snippets to facilitate hands-on learning, making it an ideal resource for anyone looking to enhance their data analysis capabilities in the sports domain. By the end of the project, users will be able to perform robust EDA, gaining valuable insights that can inform decision-making and strategy in sports analytics.
</br></br>:red_circle: **Dataset** : Will be given in the Pull Request file.
</br></br>:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.
</br></br>🔴 **Reference Project Folder**: NA

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Somnath Shaw
- GitHub Profile Link : https://github.com/SOMNATH0904
- Participant ID (If not, then put NA) : NA
- Approach for this Project : 1) Data Cleaning 2) Data Preprocessing 3) Model Training 4) Predictions and Testing
- What is your participant role? (Mention the Open Source Program name. Eg. HRSoC, GSSoC, GSOC etc.) GSSOC Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhisheks008** [comment]
Can you share the dataset? Please be specific with the sports you are analyzing for this problem statement.

**Comment by SOMNATH0904** [comment]
I have used these two datasets for the above mentioned project.
[matches.csv](https://github.com/user-attachments/files/16398390/matches.csv)
[deliveries.csv](https://github.com/user-attachments/files/16398388/deliveries.csv)

**Comment by abhisheks008** [comment]
What are the aspects of Cricket you are planning to analyze here? @SOMNATH0904

**Comment by SOMNATH0904** [comment]
In this project, I plan to analyze various aspects, including player performance metrics such as batting averages, strike rates, and bowling economy rates. Additionally, I will examine team performance by analyzing win/loss ratios, match outcomes, and scoring patterns. Fielding statistics, player consistency, and performance trends over time will also be explored to provide a comprehensive overview of cricket dynamics.

**Comment by abhisheks008** [comment]
Cool. Go ahead @SOMNATH0904
