### ISSUE TITLE
Vehicle Insurance Claim Fraud Detection

### ISSUE THREAD

**Issue by krishna-NIT** [abhisheks008/ML-Crate#73]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Vehicle Insurance Claim Fraud Detection
:red_circle: **Aim** : Vehicle insurance fraud involves conspiring to make false or exaggerated claims involving property damage or personal injuries following an accident so, It will Detect fraud claims and will help Insurance Firms to verify them properly again.
:red_circle: **Dataset** : https://www.kaggle.com/shivamb/vehicle-claim-fraud-detection
:red_circle: **Approach** : Starting with cleaning and EDA I'll be going with Classification & SGD Classifier and will try to finalize the one with the highest accuracy

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/abhisheks008/ML-Crate/tree/main/Project-Demo-Folder

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shrikrushna Bhagwat
- GitHub Profile Link : https://github.com/krishna-NIT
- Participant ID : 930 
- Approach for this Project : Starting with cleaning and EDA I'll be going with Classification & SGD Classifier and will try to finalize the one with the highest accuracy
- Are you a participant of SWOC 2.0?
    - [x] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by krishna-NIT** [comment]
I wanna start with this, Kindly please assign it to me so that I can move ahead

**Comment by abhisheks008** [comment]
Can you mention the particulars as mentioned in the issue guidelines @krishna-NIT

**Comment by abhisheks008** [comment]
@krishna-NIT do you wanna do this project?

**Comment by tandrimasingha** [comment]
Full name : Tandrima Singha
GitHub Profile Link: https://github.com/tandrimasingha
Participant ID: 1044
Approach for this Project: This is a classification problem where I need to detect fraud detection using XGBoost, Decision Tree, and Random Forest.
Are you a participant in SWOC 2.0?
YES

**Comment by krishna-NIT** [comment]
> @krishna-NIT do you wanna do this project?

Yes sure, Please assign me, so that I'll make pr
I am already done with some part in my local machine

**Comment by abhisheks008** [comment]
@tandrimasingha this issue already assigned to @krishna-NIT. You can try out other issues.

**Comment by tandrimasingha** [comment]
Sir I commented first in a proper manner.

**Comment by krishna-NIT** [comment]
Data Set has int64(9), object(24)
These 24 Columns are taking time, will complete it soon
Sorry for delay
