### ISSUE TITLE
Cricket Shots detection

### ISSUE THREAD

**Issue by ayan-joshi** [abhisheks008/ML-Crate#731]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Cricket Shot detection 
:red_circle: **Aim** : The project focuses on classification of different cricket shots using various Deep Learning Algorithms.
:red_circle: **Dataset** : https://www.kaggle.com/datasets/aneesh10/cricket-shot-dataset
:red_circle: **Approach** : I'll use ResNet , DenseNet ,InceptionNet deep learning algorithm to get the best solution for the detection of cricket shots 

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

@abhisheks008 Assign me this issue Looking forward to contribute

**Comment by abhisheks008** [comment]
Deep learning models will not work here, as this project repository mainly focuses on basic to intermediate level machine learning projects.
