### ISSUE TITLE
Next Word Prediction

### ISSUE THREAD

**Issue by neelshah2409** [abhisheks008/ML-Crate#79]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Next Word Prediction
:red_circle: **Aim** : To predict the next word according to the data present and collected in our database. 
:red_circle: **Dataset** : https://drive.google.com/file/d/1GeUzNVqiixXHnTl8oNiQ2W3CynX_lsu2/view
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/abhisheks008/ML-Crate/tree/main/Project-Demo-Folder

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- Are you a participant of SWOC 2.0?
    - [ ] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by PurnaChandraMansingh** [comment]
I have registered for JGEC Winter of code, can I work on this?

**Comment by abhisheks008** [comment]
Yes @PurnaChandraMansingh you can, wait for the coding period to start from Feb 1.

**Comment by PurnaChandraMansingh** [comment]
Ok, Thank you

**Comment by skartikc** [comment]
Full name : Kartik Chauhan
GitHub Profile Link : https://github.com/skartikc
Participant ID : N/A
Approach for this Project : 
Preprocess the given dataset - clean, generate tokens, stem, lemmatize each word and apply different approaches for vectorization - GloVe, TF-IDF, etc. Generate a vocabulary to predict the work from and use, compare different algorithms for next word prediction with visualizations.
Are you a participant of SWOC 2.0? - NO

**Comment by abhisheks008** [comment]
Are you contributing here for any open source program? @skartikc

**Comment by skartikc** [comment]
i am not currently a part of any open source program, but i want to contribute, how should i proceed?

**Comment by abhisheks008** [comment]
Okay first of all thanks for approaching this project repo.
Follow the guidelines written in the issue itself and comment out here accordingly with your credentials and approach for solving this project. If that feels appealing to me, I'll assign this to you. After that you can start working on it.

Sorry for the late reply @skartikc

**Comment by skartikc** [comment]
Full name : Kartik Chauhan
GitHub Profile Link : https://github.com/skartikc
Participant ID : N/A
Approach for this Project :
Preprocess the given dataset - clean, generate tokens, stem, lemmatize each word and apply different approaches for vectorization - GloVe, TF-IDF, etc. Generate a vocabulary to predict the work from and use, compare different algorithms for next word prediction with visualizations.
Are you a participant of SWOC 2.0? - NO

**Comment by abhisheks008** [comment]
Sounds good to me. Issue assigned to you @skartikc.

Best wishes!

**Comment by abhisheks008** [comment]
@skartikc updates regarding this issue.

**Comment by skartikc** [comment]
I have been working on this issue for the past week, learned a lot of text vectorizing techniques and exploring various combination of those with different models (RNN, LSTM). I have forked the repo and committing changes daily to it, my next step will be the final 2 model training.

**Comment by abhisheks008** [comment]
Sounds great. Keep learning and make sure you complete the project as early as possible.
@skartikc
