### ISSUE TITLE
Wine Quality Prediction

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#9]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Wine Quality Prediction
:red_circle: **Aim** : Perform various different machine learning algorithms like regression, decision tree, random forests, etc and differentiate between the models and analyse their performances.
:red_circle: **Dataset** : https://archive.ics.uci.edu/ml/datasets/wine+quality
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.
* A Demo Project has been created to guide you about the whole structure of presenting the Project in this repository. Here's the link of the Demo Project - https://github.com/abhisheks008/ML-Crate/tree/main/Project-Demo-Folder

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- Are you a participant of SWOC 2.0?
    - [ ] YES
    - [ ]  No

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by deepthi1107** [comment]
Full name : Deepthi M
GitHub Profile Link : https://github.com/deepthi1107
Participant ID : 294
Approach for this Project : Deatiled EDA, SWM, Linear regression, Desicion tree models will be used to predict the outcome.
Are you a participant of SWOC 2.0?
 YES

**Comment by abhisheks008** [comment]
Issue assigned to you @deepthi1107
