### ISSUE TITLE
Digit Recognizer Project

### ISSUE THREAD

**Issue by abhisheks008** [abhisheks008/ML-Crate#98]
### ML-Crate Repository (Proposing new issue)
:red_circle: **Project Title** : Digit Recognizer Project
:red_circle: **Aim** : Create a Machine Learning model which will predict the digits as per the user input.
:red_circle: **Dataset** : https://www.kaggle.com/c/digit-recognizer/data
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

Hello, ML-Crate contributors, this issue is only for the contribution purposes and allocated only to the participants of SWOC 2.0 Open Source Program and JWOC '22 Open Source Program.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.
- This issue is only for 'SWOC' and 'JWOC' contributors of 'ML-Crate' project.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- GitHub Profile Link : 
- Participant ID :
- Approach for this Project :
- What is your participant role?
    - [ ] SWOC 2.0 Participant.
    - [ ] JWOC 2022 Participant.
    - [ ] Contributor

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by PurnaChandraMansingh** [comment]
I have registered for JGEC Winter of code, can I work on this?

**Comment by srini047** [comment]
I want to work on this issue under JWOC.

Name: Sriniketh J
GitHub Username: srini047

**Comment by abhisheks008** [comment]
Tell me your approach for this project and also follow the guidelines in the issue, then mention all the details properly @srini047

**Comment by srini047** [comment]
- Full Name: Sriniketh J
- GitHub Profile Link : [srini047](https://github.com/srini047/)
- Participant ID: 
- Approach for this Project: Brief about MNIST Dataset and different models (one basic and one CNN based) and their accuracy and finally the best model with Conclusion.
- Participant Role: **JWOC**

**Comment by abhisheks008** [comment]
Issue assigned to you @srini047
